#!/bin/bash
# =============================================================
# SunSea Steel Website - One-Click Server Setup
# Domain: www.sunseasteel.com  IP: 43.159.129.164
# Usage:  bash server-setup.sh
# =============================================================
set -e

# Colors
G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; R='\033[0;31m'; N='\033[0m'
ok()   { echo -e "${G}[OK] $1${N}"; }
info() { echo -e "${B}[..] $1${N}"; }
warn() { echo -e "${Y}[!!] $1${N}"; }
die()  { echo -e "${R}[ERR] $1${N}"; exit 1; }

# Auto sudo detection
if [ "$EUID" -eq 0 ]; then
  SUDO=""
else
  SUDO="sudo"
  warn "Running as ubuntu, will use sudo for system commands"
  sudo -v 2>/dev/null || die "sudo not available. Try: sudo bash server-setup.sh"
fi

REPO="https://github.com/jameson99799/steel-trader-website.git"
DIR="/www/wwwroot/steel-trader"
DOMAIN="www.sunseasteel.com"
PORT=3001

echo ""
echo "=============================================="
echo "  SunSea Steel - Server Setup"
echo "  Domain : $DOMAIN"
echo "  Dir    : $DIR"
echo "=============================================="
echo ""

# 1. Node.js 20
if ! command -v node &>/dev/null; then
  info "Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | $SUDO bash - >/dev/null 2>&1
  $SUDO apt-get install -y nodejs >/dev/null 2>&1
fi
ok "Node.js $(node --version)"

# 2. Git
if ! command -v git &>/dev/null; then
  info "Installing Git..."
  $SUDO apt-get install -y git >/dev/null 2>&1
fi
ok "Git ready"

# 3. PM2
if ! command -v pm2 &>/dev/null; then
  info "Installing PM2..."
  $SUDO npm install -g pm2 >/dev/null 2>&1
fi
ok "PM2 $(pm2 --version)"

# 4. Nginx
if ! command -v nginx &>/dev/null; then
  info "Installing Nginx..."
  $SUDO apt-get install -y nginx >/dev/null 2>&1
fi
ok "Nginx ready"

# 5. Clone or update code
$SUDO mkdir -p "$DIR"
$SUDO chown -R "$(whoami)" "$DIR"

if [ -d "$DIR/.git" ]; then
  info "Updating existing repo..."
  cd "$DIR" && git pull
else
  info "Cloning from GitHub..."
  git clone "$REPO" "$DIR"
  cd "$DIR"
fi
ok "Code: $(git log --oneline -1)"

# 6. Install dependencies
info "npm install..."
npm install >/dev/null 2>&1
ok "Dependencies installed"

# 7. Build frontend
info "npm run build..."
npm run build
ok "Frontend built"

# 8. Create required directories
mkdir -p data uploads logs

# 9. Create .env file
if [ ! -f .env ]; then
  JWT=$(head /dev/urandom | tr -dc 'A-Za-z0-9!@#$%' | head -c 48)
  cat > .env << ENVEOF
NODE_ENV=production
PORT=${PORT}
JWT_SECRET=${JWT}
ENVEOF
  ok ".env created (JWT_SECRET auto-generated)"
else
  ok ".env exists"
fi

# 10. PM2 ecosystem config
cat > ecosystem.config.cjs << 'ECOEOF'
module.exports = {
  apps: [{
    name: 'led-trade',
    script: 'server/index.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 3001
    },
    error_file: './logs/err.log',
    out_file: './logs/out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    autorestart: true,
    watch: false,
    max_memory_restart: '500M'
  }]
}
ECOEOF

# 11. Start PM2
info "Starting PM2..."
pm2 delete led-trade 2>/dev/null || true
pm2 start ecosystem.config.cjs
pm2 save >/dev/null 2>&1
ok "PM2 started"

# 12. PM2 auto-start on reboot
info "Setting up PM2 auto-start..."
PM2_PATH=$(which pm2)
NODE_PATH=$(which node)
NODE_DIR=$(dirname "$NODE_PATH")
$SUDO env PATH="$PATH:$NODE_DIR" "$PM2_PATH" startup systemd -u "$(whoami)" --hp "$HOME" 2>/dev/null \
  && ok "PM2 auto-start enabled" \
  || warn "PM2 startup skipped (run manually: sudo pm2 startup)"

# 13. Nginx configuration
info "Configuring Nginx..."
$SUDO tee /etc/nginx/sites-available/steel-trader >/dev/null << NGINXCONF
server {
    listen 80;
    server_name ${DOMAIN} sunseasteel.com 43.159.129.164;
    client_max_body_size 20M;

    # Static frontend
    location / {
        root ${DIR}/dist;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    # Cached assets
    location /assets/ {
        root ${DIR}/dist;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # API proxy to Node.js
    location /api/ {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_connect_timeout 30s;
        proxy_read_timeout 300s;
    }

    # Uploaded files
    location /uploads/ {
        alias ${DIR}/uploads/;
        expires 30d;
    }

    # Sitemap (generated by Node)
    location = /sitemap.xml {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_set_header Host \$host;
    }
}
NGINXCONF

$SUDO ln -sf /etc/nginx/sites-available/steel-trader /etc/nginx/sites-enabled/steel-trader
$SUDO rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
$SUDO nginx -t && $SUDO systemctl enable nginx && $SUDO systemctl restart nginx
ok "Nginx configured and started"

# 14. Firewall
$SUDO ufw allow 22/tcp  2>/dev/null || true
$SUDO ufw allow 80/tcp  2>/dev/null || true
$SUDO ufw allow 443/tcp 2>/dev/null || true

# Done
echo ""
echo "=============================================="
echo -e "${G}  Setup Complete!${N}"
echo "=============================================="
echo ""
echo "  Website : http://${DOMAIN}"
echo "  Admin   : http://${DOMAIN}/admin/login"
echo "  Login   : admin / admin123"
echo ""
echo -e "${Y}  IMPORTANT: Change the admin password now!${N}"
echo ""
echo "  PM2 commands:"
echo "    pm2 status           # check status"
echo "    pm2 logs led-trade   # view logs"
echo "    pm2 restart led-trade"
echo ""
echo "  Update code anytime:"
echo "    cd ${DIR} && bash server-update.sh"
echo ""
