import express from 'express'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'
import { execSync } from 'child_process'
import { authMiddleware } from '../middleware/auth.js'

const router = express.Router()
const __dirname = dirname(fileURLToPath(import.meta.url))
const SSL_DIR = join(__dirname, '..', '..', 'ssl')

// Ensure ssl directory exists
if (!fs.existsSync(SSL_DIR)) fs.mkdirSync(SSL_DIR, { recursive: true })

// Nginx config template for sunseasteel.com
function generateNginxConf(certPath, keyPath) {
    return `# Auto-generated by SunSea Steel admin panel
# Do not edit manually — changes will be overwritten on next SSL upload

server {
    listen 80;
    server_name sunseasteel.com www.sunseasteel.com;
    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name sunseasteel.com www.sunseasteel.com;

    ssl_certificate     ${certPath};
    ssl_certificate_key ${keyPath};

    # SSL security settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # HSTS (optional, uncomment after confirming HTTPS works)
    # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        client_max_body_size 50m;
    }
}
`
}

// Get SSL status
router.get('/ssl/status', authMiddleware, (req, res) => {
    const certFile = join(SSL_DIR, 'cert.pem')
    const keyFile = join(SSL_DIR, 'key.pem')
    const hasCert = fs.existsSync(certFile)
    const hasKey = fs.existsSync(keyFile)

    let certInfo = null
    if (hasCert) {
        const stat = fs.statSync(certFile)
        certInfo = { size: stat.size, modified: stat.mtime }
    }

    // Check if Nginx SSL config exists — try multiple common paths + nginx -T fallback
    let nginxConfigured = false
    try {
        if (fs.existsSync('/etc/nginx/sites-enabled/sunseasteel-ssl.conf')) nginxConfigured = true
        if (!nginxConfigured && fs.existsSync('/etc/nginx/conf.d/sunseasteel-ssl.conf')) nginxConfigured = true
        if (!nginxConfigured) {
            try {
                const nginxT = execSync('nginx -T 2>/dev/null || true', { timeout: 5000 }).toString()
                if (nginxT.includes('ssl_certificate') && nginxT.includes('sunseasteel')) nginxConfigured = true
            } catch (e) { }
        }
    } catch (e) { }

    res.json({ hasCert, hasKey, certInfo, nginxConfigured })
})

// Upload SSL cert and key, configure Nginx, reload
router.post('/ssl/upload', authMiddleware, express.json({ limit: '1mb' }), (req, res) => {
    try {
        const { cert, key } = req.body
        if (!cert || !key) return res.status(400).json({ error: '请提供证书和私钥' })

        // Basic validation
        if (!cert.includes('-----BEGIN CERTIFICATE-----')) {
            return res.status(400).json({ error: '证书格式无效，请使用 PEM 格式（以 -----BEGIN CERTIFICATE----- 开头）' })
        }
        if (!key.includes('-----BEGIN') || !key.includes('PRIVATE KEY-----')) {
            return res.status(400).json({ error: '私钥格式无效，请使用 PEM 格式' })
        }

        const certPath = join(SSL_DIR, 'cert.pem')
        const keyPath = join(SSL_DIR, 'key.pem')

        // Save cert and key
        fs.writeFileSync(certPath, cert.trim() + '\n', 'utf8')
        fs.writeFileSync(keyPath, key.trim() + '\n', 'utf8')

        // Generate Nginx config
        const nginxConf = generateNginxConf(certPath, keyPath)
        const nginxConfPath = join(SSL_DIR, 'sunseasteel-ssl.conf')
        fs.writeFileSync(nginxConfPath, nginxConf, 'utf8')

        // Try to install Nginx config and reload
        let nginxStatus = 'manual'
        let nginxMessage = ''
        try {
            // Copy config to Nginx sites-available
            execSync(`sudo cp ${nginxConfPath} /etc/nginx/sites-available/sunseasteel-ssl.conf`, { timeout: 5000 })
            // Enable it
            execSync(`sudo ln -sf /etc/nginx/sites-available/sunseasteel-ssl.conf /etc/nginx/sites-enabled/sunseasteel-ssl.conf`, { timeout: 5000 })

            // Remove default config if it exists (to avoid conflicts)
            try {
                execSync('sudo rm -f /etc/nginx/sites-enabled/default', { timeout: 5000 })
            } catch (e) { }

            // Test Nginx config
            const testResult = execSync('sudo nginx -t 2>&1', { timeout: 10000 }).toString()
            if (testResult.includes('successful')) {
                // Reload Nginx
                execSync('sudo nginx -s reload', { timeout: 10000 })
                nginxStatus = 'success'
                nginxMessage = 'Nginx 已自动配置并重新加载，HTTPS 已生效！'
            } else {
                nginxStatus = 'test_failed'
                nginxMessage = 'Nginx 配置检测失败: ' + testResult
            }
        } catch (e) {
            nginxStatus = 'manual'
            nginxMessage = 'Nginx 自动配置需要 sudo 权限。请手动执行以下命令：\n' +
                `sudo cp ${nginxConfPath} /etc/nginx/sites-available/sunseasteel-ssl.conf\n` +
                'sudo ln -sf /etc/nginx/sites-available/sunseasteel-ssl.conf /etc/nginx/sites-enabled/\n' +
                'sudo nginx -t && sudo nginx -s reload'
        }

        res.json({
            success: true,
            message: 'SSL证书已保存！' + (nginxStatus === 'success' ? ' ' + nginxMessage : ''),
            nginxStatus,
            nginxMessage
        })
    } catch (e) {
        res.status(500).json({ error: e.message })
    }
})

// Delete SSL certs
router.delete('/ssl', authMiddleware, (req, res) => {
    try {
        const certFile = join(SSL_DIR, 'cert.pem')
        const keyFile = join(SSL_DIR, 'key.pem')
        if (fs.existsSync(certFile)) fs.unlinkSync(certFile)
        if (fs.existsSync(keyFile)) fs.unlinkSync(keyFile)

        // Try to remove Nginx SSL config
        try {
            execSync('sudo rm -f /etc/nginx/sites-enabled/sunseasteel-ssl.conf', { timeout: 5000 })
            execSync('sudo nginx -s reload', { timeout: 5000 })
        } catch (e) { }

        res.json({ success: true })
    } catch (e) {
        res.status(500).json({ error: e.message })
    }
})

export default router
