import{upload,productHtml}from'./tpl.mjs'
const C=1,S=JSON.stringify
const sp=(zn,thk,w)=>[{name:'Zinc Coating',value:zn},{name:'Thickness',value:thk},{name:'Width',value:w||'600-1500mm'},{name:'Spangle',value:'Regular / Mini / Zero'},{name:'Surface',value:'Chromated / Oiled / Passivated'},{name:'Standard',value:'ASTM A653, EN 10346, JIS G3302, GB/T 2518'}]
const apps=[{i:'🏗️',t:'Construction & Roofing',d:'Purlins, girts, roof decking, wall cladding, light gauge framing, and structural sections for buildings of all types.'},{i:'🚗',t:'Automotive & Transport',d:'Body underpanels, fuel tanks, exhaust heat shields, bus/truck bodies, trailer panels, and chassis components.'},{i:'🏭',t:'Manufacturing & HVAC',d:'Ductwork, cable trays, electrical enclosures, machine guards, storage systems, shelving, and general fabrication.'},{i:'🌾',t:'Agriculture & Infrastructure',d:'Grain silos, greenhouse frames, fencing, highway barriers, drainage pipes, culverts, and solar mounting structures.'}]
const fq=(g)=>[{q:`What zinc coating weight is ${g}?`,a:`${g} refers to the zinc coating weight in g/m² (total both sides). Higher coating = longer corrosion life. Z40≈5yr, Z100≈15yr, Z275≈25+ years in rural environments.`},{q:'What is the difference between GI and GL?',a:'GI (Galvanized) uses pure zinc coating. GL (Galvalume) uses 55% aluminum + 43.4% zinc + 1.6% silicon alloy. GL offers 2-4× longer corrosion life but GI has better cut-edge protection and is easier to solder.'},{q:'Can GI steel be painted?',a:'Yes. Chromated or phosphated GI provides excellent paint adhesion. This is the basis for PPGI (Prepainted Galvanized) production. For field painting, use zinc-chromate primer + polyurethane topcoat.'},{q:'What is the MOQ?',a:'25 MT per specification for full container loads (FCL). Mixed containers available: minimum 5 MT per spec with 25 MT total.'},{q:'What surface treatments are available?',a:'Chromated (Cr3+ or Cr6+), oiled (anti-fingerprint), passivated, phosphated, or untreated. Chemical treatment improves corrosion resistance during storage and transport.'},{q:'What is the delivery time?',a:'Production: 15-20 days from order confirmation. FOB Chinese port: 3-5 days after production. Total CIF delivery to SE Asia: 25-35 days.'}]
const P=[
{n:'热镀锌钢卷 Z40-Z60',ne:'Hot-Dip Galvanized Steel Coil Z40-Z60 Economy',zn:'Z40-Z60 (40-60 g/m²)',thk:'0.12-1.0mm',hero:'GI Steel Coil Z40-Z60',sub:'Economy Grade — Budget Roofing & Interior Applications',badges:['🛡️ Z40-Z60','📏 0.12-1.0mm','💰 Economy','🏠 Interior'],seo:{t:'GI Steel Coil Z40-Z60 Economy Grade | SunSea Steel',d:'Z40-Z60 economy galvanized steel coil for budget roofing, interior ductwork, and light fabrication. Factory direct.',k:'galvanized coil Z40, GI Z60, economy galvanized steel, cheap GI coil, budget zinc coated steel'}},
{n:'热镀锌钢卷 Z80-Z100',ne:'Hot-Dip Galvanized Steel Coil Z80-Z100 Standard',zn:'Z80-Z100 (80-100 g/m²)',thk:'0.15-2.0mm',hero:'GI Steel Coil Z80-Z100',sub:'Standard Grade — Most Popular for Construction & General Use',badges:['🛡️ Z80-Z100','📏 0.15-2.0mm','⭐ Best Seller','🏗️ Construction'],seo:{t:'GI Steel Coil Z80-Z100 Standard Grade | SunSea Steel',d:'Z80-Z100 standard galvanized steel coil. Most popular grade for construction, roofing, and manufacturing.',k:'galvanized coil Z100, GI Z80, standard galvanized, construction GI steel, zinc coated coil'}},
{n:'热镀锌钢卷 Z120-Z150',ne:'Hot-Dip Galvanized Steel Coil Z120-Z150 Heavy Coating',zn:'Z120-Z150 (120-150 g/m²)',thk:'0.20-2.5mm',hero:'GI Steel Coil Z120-Z150',sub:'Heavy Coating — Extended Life for Outdoor & Industrial Use',badges:['🛡️ Z120-Z150','📏 0.20-2.5mm','💪 Heavy Duty','🏭 Industrial'],seo:{t:'GI Steel Coil Z120-Z150 Heavy Coating | SunSea Steel',d:'Z120-Z150 heavy coating galvanized steel for outdoor structures, industrial roofing, and harsh environments.',k:'galvanized Z150, heavy zinc coating, GI Z120, industrial galvanized, outdoor zinc steel'}},
{n:'热镀锌钢卷 Z180-Z200',ne:'Hot-Dip Galvanized Steel Coil Z180-Z200 Premium',zn:'Z180-Z200 (180-200 g/m²)',thk:'0.25-3.0mm',hero:'GI Steel Coil Z180-Z200',sub:'Premium Grade — Maximum Protection for Demanding Environments',badges:['🛡️ Z180-Z200','📏 0.25-3.0mm','💎 Premium','🌊 Coastal'],seo:{t:'GI Steel Coil Z180-Z200 Premium Grade | SunSea Steel',d:'Z180-Z200 premium galvanized steel for coastal, marine, and chemically aggressive environments. 20+ year life.',k:'galvanized Z200, premium GI coil, Z180 zinc steel, coastal galvanized, marine grade GI'}},
{n:'热镀锌钢卷 Z275',ne:'Hot-Dip Galvanized Steel Coil Z275 Maximum',zn:'Z275 (275 g/m²)',thk:'0.30-3.0mm',hero:'GI Steel Coil Z275',sub:'Maximum Zinc — The Heaviest Standard Coating for Extreme Durability',badges:['🛡️ Z275 Max','📏 0.30-3.0mm','🏆 Heaviest Coating','⏳ 25+ Years'],seo:{t:'GI Steel Coil Z275 Maximum Zinc Coating | SunSea Steel',d:'Z275 maximum zinc coating galvanized steel coil. Heaviest standard coating for extreme durability and 25+ year service life.',k:'galvanized Z275, maximum zinc coating, Z275 GI coil, heaviest galvanized, extreme durability GI'}},
{n:'零锌花镀锌钢卷',ne:'Zero Spangle Galvanized Steel Coil',zn:'Z100-Z275',thk:'0.20-1.5mm',hero:'Zero Spangle GI Steel',sub:'Smooth Matte Finish — Perfect Base for Painting & Laminating',badges:['✨ Zero Spangle','🎨 Paint Ready','📏 0.20-1.5mm','🏠 Appliance'],seo:{t:'Zero Spangle Galvanized Steel Coil | SunSea Steel',d:'Zero spangle galvanized steel with smooth matte surface. Ideal for painting, laminating, and appliance manufacturing.',k:'zero spangle galvanized, smooth GI coil, paint grade galvanized, matte zinc steel, appliance GI'}},
{n:'小锌花镀锌钢卷',ne:'Minimized Spangle Galvanized Steel Coil',zn:'Z100-Z200',thk:'0.20-1.5mm',hero:'Minimized Spangle GI Steel',sub:'Fine Grain Surface — Good Compromise Between Cost & Appearance',badges:['✨ Mini Spangle','📏 0.20-1.5mm','🔧 Versatile','💰 Value'],seo:{t:'Minimized Spangle Galvanized Steel Coil | SunSea Steel',d:'Minimized spangle galvanized steel coil. Fine grain surface for improved appearance at lower cost than zero spangle.',k:'minimized spangle GI, mini spangle galvanized, fine grain zinc, small spangle steel coil'}},
{n:'结构用镀锌钢卷 S350GD',ne:'Structural Galvanized Steel Coil S350GD+Z',zn:'Z100-Z275',thk:'0.50-3.0mm',hero:'Structural GI S350GD',sub:'High Yield Strength 350MPa — Structural Framing & Purlins',badges:['💪 350MPa Yield','🏗️ Structural','📏 0.50-3.0mm','📋 EN 10346'],seo:{t:'Structural Galvanized Steel S350GD | SunSea Steel',d:'S350GD+Z structural galvanized steel. 350MPa yield strength for purlins, girts, studs, and structural framing.',k:'S350GD galvanized, structural GI steel, high strength galvanized, purlin steel, structural zinc coated'}},
{n:'深冲用镀锌钢卷 DX54D',ne:'Deep Drawing Galvanized Steel Coil DX54D+Z',zn:'Z100-Z200',thk:'0.40-2.0mm',hero:'Deep Drawing GI DX54D',sub:'Extra Deep Drawing Quality — Automotive & Complex Forming',badges:['🔩 Deep Drawing','🚗 Automotive','📏 0.40-2.0mm','📋 EN 10346'],seo:{t:'Deep Drawing Galvanized Steel DX54D | SunSea Steel',d:'DX54D+Z deep drawing galvanized steel for automotive panels, complex stampings, and precision forming applications.',k:'DX54D galvanized, deep drawing GI, automotive galvanized, formable zinc steel, stamping GI coil'}},
{n:'商用镀锌钢卷 SGCC',ne:'Commercial Quality Galvanized Steel Coil SGCC',zn:'Z60-Z180',thk:'0.12-1.2mm',hero:'Commercial GI SGCC',sub:'JIS Standard Commercial Quality — General Purpose Manufacturing',badges:['📋 JIS G3302','📏 0.12-1.2mm','🔧 General Use','🌏 Popular'],seo:{t:'SGCC Commercial Galvanized Steel Coil | SunSea Steel',d:'SGCC commercial quality galvanized steel per JIS G3302. General purpose GI for manufacturing and construction.',k:'SGCC galvanized, JIS galvanized steel, commercial GI coil, SGCC zinc steel, JIS G3302 GI'}},
{n:'镀锌钢板',ne:'Galvanized Steel Sheet — Flat Cut to Size',zn:'Z60-Z275',thk:'0.30-3.0mm',hero:'GI Steel Sheet',sub:'Pre-Cut Flat Panels — Ready for Fabrication & Installation',badges:['📐 Custom Cut','📏 1000-6000mm','🔧 Fab Ready','📦 Palletized'],seo:{t:'Galvanized Steel Sheet Flat Cut | SunSea Steel',d:'Galvanized steel sheet cut to size. Z60-Z275 coating. For roofing, cladding, fabrication, and construction projects.',k:'galvanized steel sheet, GI flat sheet, zinc coated sheet, cut to size galvanized, GI panel'}},
{n:'镀锌钢带',ne:'Galvanized Steel Strip — Precision Slit',zn:'Z60-Z275',thk:'0.15-3.0mm, Width 20-600mm',hero:'GI Steel Strip',sub:'Precision Slit Narrow Strip — Tube Making, Stamping & Components',badges:['📐 20-600mm Width','🔧 ±0.05mm','🔩 Tube Making','📏 0.15-3.0mm'],seo:{t:'Galvanized Steel Strip Precision Slit | SunSea Steel',d:'Precision slit galvanized steel strip for tube welding, cable armor, stamping, and component manufacturing.',k:'galvanized steel strip, GI slit coil, narrow zinc strip, tube making strip, precision GI strip'}},
{n:'耐指纹镀锌钢卷',ne:'Anti-Fingerprint Galvanized Steel Coil (AFP GI)',zn:'Z80-Z200',thk:'0.20-1.2mm',hero:'AFP Galvanized Steel',sub:'Anti-Fingerprint Treatment — Clean Handling & Enhanced Corrosion Resistance',badges:['🖐️ Anti-Fingerprint','✨ Clean Surface','📏 0.20-1.2mm','🏠 Appliance'],seo:{t:'Anti-Fingerprint Galvanized Steel AFP GI | SunSea Steel',d:'AFP anti-fingerprint galvanized steel coil. Clean handling, enhanced corrosion resistance for appliances and visible surfaces.',k:'anti-fingerprint galvanized, AFP GI steel, fingerprint free zinc, clean surface GI, AFP coated steel'}},
{n:'花纹镀锌钢板',ne:'Galvanized Checkered Steel Plate (Diamond Pattern)',zn:'Z60-Z150',thk:'1.5-6.0mm',hero:'GI Checkered Plate',sub:'Diamond Pattern Non-Slip Surface — Flooring & Platform Applications',badges:['◆ Diamond Pattern','🦶 Non-Slip','📏 1.5-6.0mm','🏭 Industrial'],seo:{t:'Galvanized Checkered Steel Plate | SunSea Steel',d:'Galvanized diamond pattern checkered plate for non-slip flooring, platforms, stair treads, and vehicle decking.',k:'galvanized checkered plate, diamond plate zinc, non-slip GI plate, GI tread plate, patterned galvanized'}},
{n:'镀锌波纹管用钢带',ne:'Galvanized Steel Strip for Corrugated Pipe Manufacturing',zn:'Z100-Z275',thk:'0.50-3.0mm, Width 125-400mm',hero:'GI Strip for Corrugated Pipe',sub:'Specialized Strip for Helical Corrugated Drainage & Culvert Pipes',badges:['🔧 Pipe Grade','📏 125-400mm','💪 Z100-Z275','🌊 Drainage'],seo:{t:'Galvanized Steel Strip for Corrugated Pipe | SunSea Steel',d:'Galvanized steel strip for helical corrugated pipe manufacturing. Z100-Z275 coating for drainage culverts.',k:'corrugated pipe steel, GI strip for pipe, culvert steel strip, drainage pipe galvanized, helical pipe strip'}}
]
async function main(){
  let c=0
  for(const p of P){
    const ov=`<p><strong>${p.ne}</strong> with ${p.zn} zinc coating and ${p.thk} thickness range. Manufactured on our advanced continuous galvanizing line (CGL) with precise coating weight control and uniform zinc distribution across the full strip width.</p><p>Available in regular, minimized, and zero spangle finishes. All coils supplied with Mill Test Certificate per EN 10204 Type 3.1. Custom width, coating weight, and surface treatment to your specifications.</p>`
    const data={name:p.n,name_en:p.ne,category_id:C,description:p.ne,description_en:p.ne,
      specs:S(sp(p.zn,p.thk)),faq_items:S(fq(p.zn).map(f=>({question:f.q,answer:f.a}))),is_featured:c<3?1:0,status:1,
      seo_title:p.seo.t,seo_description:p.seo.d,seo_keywords:p.seo.k,
      detail_content:productHtml({name:p.n,name_en:p.ne,hero:p.hero,sub:p.sub,badges:p.badges,accent:'#e67e22',
        overview:ov,specs:sp(p.zn,p.thk),apps,faqs:fq(p.zn)})}
    const r=await upload('products',data);c++
    console.log(`✅ [${c}/15] ${p.ne} → id=${r.id}`)
  }
  console.log(`\n🎉 Cat1 GI: ${c} products done`)
}
main().catch(e=>console.error('❌',e))
