import{upload,productHtml}from'./tpl.mjs'
const C=2,S=JSON.stringify
const sp=(az,thk,w)=>[{name:'Al-Zn Coating',value:az},{name:'Thickness',value:thk},{name:'Width',value:w||'600-1500mm'},{name:'Coating Composition',value:'55% Al + 43.4% Zn + 1.6% Si'},{name:'Surface',value:'Regular Spangle / AFP / Chromated'},{name:'Standard',value:'ASTM A792, EN 10346, JIS G3321, AS 1397'}]
const apps=[{i:'🏠',t:'Roofing & Cladding',d:'Premium residential and commercial roofing sheets, wall cladding, fascia, and soffit panels. 2-4× longer life than GI in the same application.'},{i:'☀️',t:'Solar & Renewable Energy',d:'PV mounting brackets, tracker structures, ground screws, cable management systems. AZ150+ for 25-year warranty matching solar panel life.'},{i:'🏗️',t:'Pre-Engineered Buildings',d:'Wall and roof sheeting for PEB/pre-fab steel buildings. IBR, corrugated, and standing seam profiles for industrial and commercial structures.'},{i:'🌡️',t:'High Temperature Applications',d:'Exhaust systems, oven components, heat exchangers, chimney liners. GL withstands 315°C continuous vs 230°C for GI.'}]
const fq=(az)=>[{q:`What does ${az} coating mean?`,a:`${az} indicates the total coating weight in g/m² (both sides). AZ150 means 150g/m² total Al-Zn alloy. Per side, this equals approximately 25μm coating thickness.`},{q:'How does GL compare to GI in corrosion resistance?',a:'GL (Galvalume) provides 2-4× longer flat-panel corrosion life than GI of equivalent coating weight. However, GI has superior cut-edge protection. GL AZ150 typically lasts 30-40 years in rural environments vs 15-20 years for GI Z150.'},{q:'What is the maximum temperature for GL?',a:'GL can withstand continuous temperatures up to 315°C vs 230°C for GI. Above 315°C, the aluminum-zinc alloy layer begins to degrade. This makes GL ideal for exhaust systems and heat-related applications.'},{q:'Can GL be welded?',a:'Yes, but it requires more care than GI. Use MIG with silicon-bronze wire or covered electrodes with flux designed for aluminum-coated steel. Standard carbon steel MIG wire causes aluminum contamination in the weld pool.'},{q:'What is the minimum order quantity?',a:'25 MT per specification for FCL. Mixed containers: 5 MT/spec minimum with 25 MT total. Trial orders from 5 MT available at slightly higher pricing.'},{q:'What surface finishes are available?',a:'Regular mill finish, anti-fingerprint (AFP — clear acrylic resin coating for clean handling), chromated (Cr3+ passivation), or passivated. AFP recommended for visible applications.'}]
const P=[
{n:'镀铝锌钢卷 AZ50',ne:'Galvalume Steel Coil AZ50 - Light Coating',az:'AZ50 (50 g/m²)',thk:'0.15-1.0mm',hero:'GL Steel Coil AZ50',sub:'Light Coating — Budget Interior & Sheltered Applications',badges:['🛡️ AZ50','📏 0.15-1.0mm','💰 Economy','🏠 Interior'],seo:{t:'Galvalume Steel Coil AZ50 Light Coating | SunSea Steel',d:'AZ50 Galvalume steel coil for budget interior and sheltered applications. 55%Al-Zn alloy coating. Factory direct.',k:'galvalume AZ50, aluzinc AZ50, light coating GL, budget galvalume, economy GL coil'}},
{n:'镀铝锌钢卷 AZ70',ne:'Galvalume Steel Coil AZ70 - Standard Light',az:'AZ70 (70 g/m²)',thk:'0.20-1.5mm',hero:'GL Steel Coil AZ70',sub:'Standard Light — Sheltered Exterior & Light Commercial',badges:['🛡️ AZ70','📏 0.20-1.5mm','🏗️ Light Commercial','📊 15-20yr'],seo:{t:'Galvalume Steel Coil AZ70 Standard | SunSea Steel',d:'AZ70 standard Galvalume steel coil for sheltered exterior and light commercial roofing applications.',k:'galvalume AZ70, aluzinc AZ70, standard GL, light commercial galvalume, GL roofing'}},
{n:'镀铝锌钢卷 AZ100',ne:'Galvalume Steel Coil AZ100 - Standard',az:'AZ100 (100 g/m²)',thk:'0.25-2.0mm',hero:'GL Steel Coil AZ100',sub:'Standard Grade — General Roofing & Industrial Cladding',badges:['🛡️ AZ100','📏 0.25-2.0mm','⭐ Standard','🏭 Industrial'],seo:{t:'Galvalume Steel Coil AZ100 Standard Grade | SunSea Steel',d:'AZ100 Galvalume steel coil. Standard grade for general roofing, industrial cladding, and wall panels.',k:'galvalume AZ100, aluzinc AZ100, standard galvalume coil, GL roofing steel, industrial cladding GL'}},
{n:'镀铝锌钢卷 AZ150',ne:'Galvalume Steel Coil AZ150 - Heavy Coating',az:'AZ150 (150 g/m²)',thk:'0.30-3.0mm',hero:'GL Steel Coil AZ150',sub:'Heavy Coating — Premium Roofing, Solar & 30+ Year Projects',badges:['🛡️ AZ150','📏 0.30-3.0mm','💎 Premium','☀️ Solar Grade'],seo:{t:'Galvalume Steel Coil AZ150 Heavy Coating Premium | SunSea Steel',d:'AZ150 premium Galvalume for 30+ year roofing, solar structures, and demanding environments. Heavy Al-Zn coating.',k:'galvalume AZ150, premium GL coil, heavy coating galvalume, solar grade GL, AZ150 roofing'}},
{n:'镀铝锌钢卷 AZ185',ne:'Galvalume Steel Coil AZ185 - Maximum Coating',az:'AZ185 (185 g/m²)',thk:'0.35-3.0mm',hero:'GL Steel Coil AZ185',sub:'Maximum Coating — Extreme Durability for Coastal & Marine',badges:['🛡️ AZ185 Max','📏 0.35-3.0mm','🏆 Heaviest','🌊 Coastal/Marine'],seo:{t:'Galvalume Steel Coil AZ185 Maximum Coating | SunSea Steel',d:'AZ185 maximum coating Galvalume for coastal, marine, and extreme exposure. Longest possible GL service life.',k:'galvalume AZ185, maximum GL coating, coastal galvalume, marine GL steel, extreme durability GL'}},
{n:'耐指纹镀铝锌钢卷',ne:'Anti-Fingerprint Galvalume Steel Coil (AFP GL)',az:'AZ100-AZ185',thk:'0.20-1.5mm',hero:'AFP Galvalume Steel',sub:'Anti-Fingerprint Coating — Clean Handling & Enhanced Surface Protection',badges:['🖐️ AFP Treated','✨ Clean Surface','📏 0.20-1.5mm','🏠 Visible Use'],seo:{t:'Anti-Fingerprint AFP Galvalume Steel Coil | SunSea Steel',d:'AFP anti-fingerprint Galvalume steel coil. Clean handling with enhanced corrosion resistance for visible roofing and cladding.',k:'AFP galvalume, anti-fingerprint GL, AFP GL steel, fingerprint free aluzinc, clean surface galvalume'}},
{n:'镀铝锌钢板',ne:'Galvalume Steel Sheet — Flat Cut to Size',az:'AZ100-AZ185',thk:'0.30-3.0mm',hero:'GL Steel Sheet',sub:'Pre-Cut Flat Panels for Cladding, Fabrication & Installation',badges:['📐 Custom Cut','📏 Custom Length','🔧 Fab Ready','📦 Palletized'],seo:{t:'Galvalume Steel Sheet Flat Cut | SunSea Steel',d:'Galvalume steel sheet cut to size. AZ100-AZ185 coating for roofing, cladding, and heat shield fabrication.',k:'galvalume sheet, GL flat sheet, aluzinc sheet cut, galvalume panel, GL steel plate'}},
{n:'镀铝锌钢带',ne:'Galvalume Steel Strip — Precision Slit',az:'AZ100-AZ150',thk:'0.20-2.0mm, Width 20-600mm',hero:'GL Steel Strip',sub:'Precision Slit Strip for Tube Making, Profiles & Components',badges:['📐 20-600mm Width','🔧 ±0.05mm','🔩 Tube/Profile','📏 0.20-2.0mm'],seo:{t:'Galvalume Steel Strip Precision Slit | SunSea Steel',d:'Precision slit Galvalume steel strip for tube welding, profile roll forming, and component manufacturing.',k:'galvalume strip, GL slit coil, aluzinc narrow strip, GL tube strip, precision galvalume strip'}},
{n:'结构用镀铝锌钢卷 S350GD',ne:'Structural Galvalume Steel Coil S350GD+AZ',az:'AZ150-AZ185',thk:'0.60-3.0mm',hero:'Structural GL S350GD',sub:'High Strength 350MPa — Purlins, Girts & Structural Framing',badges:['💪 350MPa','🏗️ Structural','📏 0.60-3.0mm','📋 EN 10346'],seo:{t:'Structural Galvalume Steel S350GD | SunSea Steel',d:'S350GD+AZ structural Galvalume steel. 350MPa yield for purlins, girts, and structural framing with AZ150-AZ185.',k:'S350GD galvalume, structural GL, high strength aluzinc, GL purlin steel, structural galvalume coil'}},
{n:'屋面用镀铝锌钢卷',ne:'Galvalume Steel Coil for Roofing Applications',az:'AZ150 (Roofing Grade)',thk:'0.30-0.70mm',hero:'Roofing Grade Galvalume',sub:'Optimized for Corrugated, Trapezoidal & Standing Seam Profiles',badges:['🏠 Roofing Grade','📏 0.30-0.70mm','🛡️ AZ150','📊 30-40yr Life'],seo:{t:'Galvalume Steel Coil for Metal Roofing | SunSea Steel',d:'Roofing grade Galvalume AZ150 for corrugated, IBR, and standing seam metal roofing profiles. 30-40 year service life.',k:'galvalume for roofing, GL roofing coil, metal roof galvalume, aluzinc roofing, GL roof sheet substrate'}},
{n:'光伏支架用镀铝锌钢卷',ne:'Galvalume Steel Coil for Solar Mounting Structures',az:'AZ150-AZ185 (Solar Grade)',thk:'1.0-3.0mm',hero:'Solar Grade Galvalume',sub:'25-Year Warranty Compatible — PV Brackets, Trackers & Ground Screws',badges:['☀️ Solar Grade','📏 1.0-3.0mm','⏳ 25yr Warranty','🛡️ AZ150-185'],seo:{t:'Galvalume Steel for Solar Mounting Structures | SunSea Steel',d:'Solar grade Galvalume AZ150-AZ185 for PV mounting brackets, trackers, ground screws. 25-year warranty compatible.',k:'galvalume for solar, GL solar mounting, aluzinc PV bracket, solar grade steel, GL tracker structure'}},
{n:'HVAC暖通用镀铝锌钢卷',ne:'Galvalume Steel Coil for HVAC & Ductwork',az:'AZ70-AZ100',thk:'0.30-1.2mm',hero:'HVAC Grade Galvalume',sub:'Heat Resistant & Corrosion Proof — Duct, Plenum & Air Handler',badges:['🌡️ Heat Resistant','📏 0.30-1.2mm','🛡️ AZ70-100','🏢 HVAC'],seo:{t:'Galvalume Steel for HVAC Ductwork | SunSea Steel',d:'HVAC grade Galvalume AZ70-AZ100 for ductwork, plenums, and air handling units. Heat resistant to 315°C.',k:'galvalume HVAC, GL ductwork steel, aluzinc air duct, heat resistant GL, HVAC galvalume coil'}},
{n:'隔热用镀铝锌钢卷',ne:'Galvalume Steel for Heat Shield & Exhaust Applications',az:'AZ150 (Heat Grade)',thk:'0.40-1.5mm',hero:'Heat Shield Galvalume',sub:'Continuous 315°C — Exhaust Systems, Oven Panels & Heat Shields',badges:['🌡️ 315°C Rated','📏 0.40-1.5mm','🔥 Heat Shield','🛡️ AZ150'],seo:{t:'Galvalume Steel for Heat Shield Applications | SunSea Steel',d:'Heat grade Galvalume for exhaust systems, oven panels, heat shields. Continuous 315°C temperature rating.',k:'galvalume heat shield, GL exhaust steel, heat resistant aluzinc, oven panel GL, high temp galvalume'}},
{n:'澳标镀铝锌钢卷 AM150',ne:'Galvalume Steel Coil AM150 — Australian Standard AS 1397',az:'AM150 (AS 1397)',thk:'0.35-1.6mm (BMT)',hero:'Australian Standard GL AM150',sub:'AS 1397 Compliant — For Australian & New Zealand Construction Markets',badges:['📋 AS 1397','🇦🇺 Australian Std','📏 BMT 0.35-1.6mm','🏗️ Construction'],seo:{t:'Galvalume Steel AM150 Australian Standard AS 1397 | SunSea Steel',d:'AM150 Galvalume per Australian Standard AS 1397 for construction in Australia and New Zealand markets.',k:'AM150 galvalume, Australian standard GL, AS 1397 steel, New Zealand galvalume, AM150 roofing'}},
{n:'钝化镀铝锌钢卷',ne:'Chromated / Passivated Galvalume Steel Coil',az:'AZ100-AZ185',thk:'0.20-2.0mm',hero:'Passivated Galvalume Steel',sub:'Enhanced Surface Protection for Storage Stability & Paint Adhesion',badges:['🛡️ Passivated','📏 0.20-2.0mm','🎨 Paint Ready','📦 Storage Stable'],seo:{t:'Chromated Passivated Galvalume Steel Coil | SunSea Steel',d:'Chromated and passivated Galvalume steel coil. Enhanced storage stability and paint adhesion for PPGL production.',k:'passivated galvalume, chromated GL, GL surface treatment, paint ready galvalume, PPGL substrate'}}
]
async function main(){
  let c=0
  for(const p of P){
    const ov=`<p><strong>${p.ne}</strong> featuring ${p.az} aluminum-zinc alloy coating with ${p.thk} thickness range. The 55% aluminum + 43.4% zinc + 1.6% silicon alloy coating combines aluminum's excellent barrier protection with zinc's sacrificial protection for maximum corrosion life.</p><p>Produced on our advanced continuous Al-Zn coating line with ±5 g/m² coating weight precision. Supplied with MTC per EN 10204 Type 3.1.</p>`
    const data={name:p.n,name_en:p.ne,category_id:C,description:p.ne,description_en:p.ne,
      specs:S(sp(p.az,p.thk)),faq_items:S(fq(p.az).map(f=>({question:f.q,answer:f.a}))),is_featured:c<3?1:0,status:1,
      seo_title:p.seo.t,seo_description:p.seo.d,seo_keywords:p.seo.k,
      detail_content:productHtml({name:p.n,name_en:p.ne,hero:p.hero,sub:p.sub,badges:p.badges,accent:'#27ae60',
        overview:ov,specs:sp(p.az,p.thk),apps,faqs:fq(p.az)})}
    const r=await upload('products',data);c++
    console.log(`✅ [${c}/15] ${p.ne} → id=${r.id}`)
  }
  console.log(`\n🎉 Cat2 GL: ${c} products done`)
}
main().catch(e=>console.error('❌',e))
