import{upload,productHtml}from'./tpl.mjs'
const C=5,S=JSON.stringify
const sp=(prof,thk,sub)=>[{name:'Profile Type',value:prof},{name:'Steel Thickness (BMT)',value:thk},{name:'Substrate',value:sub||'GI Z80-Z275 / GL AZ100-AZ185'},{name:'Effective Cover Width',value:'686-1000mm'},{name:'Paint System',value:'PE / SMP / HDP / PVDF (15-35μm)'},{name:'Color',value:'Full RAL Range (200+ colors) or Bare GL'},{name:'Standard',value:'AS 1397, ASTM A653/A792, EN 10346, JIS G3302/G3321'}]
const apps=[{i:'🏠',t:'Residential Roofing',d:'Houses, villas, townhouses, apartments. Corrugated and standing seam for long-span residential. Color-matched accessories.'},{i:'🏗️',t:'Commercial & Industrial',d:'Factories, warehouses, malls, offices. Trapezoidal and IBR profiles for large-span metal buildings.'},{i:'🌾',t:'Agricultural Buildings',d:'Barns, poultry houses, greenting houses, grain storage. Corrugated GL for maximum corrosion life and heat reflection.'},{i:'🏛️',t:'Architectural & Premium',d:'Standing seam for premium commercial. Stone-coated tiles for luxury residential. Concealed fastener systems.'}]
const fq=[{q:'What profile is best for my roof?',a:'Corrugated for traditional look and budgets. Trapezoidal/IBR for industrial and long spans. Standing seam for premium (no exposed fasteners). Tile profile for residential aesthetics matching clay tiles.'},{q:'What is the minimum roof pitch?',a:'Corrugated: minimum 10° (5° with sealant). Trapezoidal: minimum 5° (3° with sealant). Standing seam: minimum 3° (1.5° with sealant). Always check local building code requirements.'},{q:'What thickness should I use?',a:'0.35mm BMT minimum budget. 0.42-0.47mm standard residential. 0.50-0.55mm premium residential/commercial. 0.60-0.70mm industrial/long span. Never use <0.35mm for external roofing.'},{q:'How long does a metal roof last?',a:'Bare GI Z150: 15-20yr. Bare GL AZ150: 30-40yr. PPGI PE: 15-20yr total system. PPGL HDP/PVDF: 30-45yr total system. Standing seam (no exposed fasteners): add 5-10yr to any of above.'},{q:'What is the MOQ for custom profiles?',a:'Standard corrugated and IBR: no MOQ, cut to your length. Custom profiles: 5MT minimum. Custom colors: 25MT minimum PPGI/PPGL coil order, then profile to any quantity.'},{q:'Do you supply accessories?',a:'Yes: ridge caps, barge/gable trim, valley gutters, fascia, downpipes, flashings, foam closures, self-drilling screws. All color-matched to roof profile.'}]
const P=[
{n:'波纹板 850型',ne:'Corrugated Roofing Sheet 850mm — Classic Wave Profile',prof:'Corrugated (Sinusoidal)',thk:'0.14-0.60mm BMT',hero:'Corrugated Roof 850',sub:'Iconic Wave Profile — The World\'s Most Popular Roofing Sheet',badges:['🌊 Wave Profile','📏 850mm Cover','⭐ #1 Global','🏠 Residential'],seo:{t:'Corrugated Roofing Sheet 850mm | SunSea Steel',d:'Classic corrugated roofing sheet 850mm cover width. GI, GL, PPGI, PPGL. The world\'s most popular metal roofing profile.',k:'corrugated roofing sheet, 850 corrugated roof, wave profile sheet, corrugated iron, metal corrugated roof'}},
{n:'梯形板 YX25-210-840',ne:'Trapezoidal/IBR Roofing Sheet 840mm — Industrial Standard',prof:'Trapezoidal IBR (25mm rib)',thk:'0.30-0.70mm BMT',hero:'Trapezoidal IBR 840',sub:'Industrial Standard Profile for Factory, Warehouse & Commercial',badges:['📐 Trapezoidal','📏 840mm Cover','🏭 Industrial','💪 Structural'],seo:{t:'Trapezoidal IBR Roofing Sheet 840mm | SunSea Steel',d:'Trapezoidal IBR roofing sheet 840mm cover. 25mm rib height for industrial and commercial metal roofing and wall cladding.',k:'trapezoidal roofing sheet, IBR roof panel, industrial roofing, 840 IBR sheet, metal deck roof'}},
{n:'梯形板 YX35-125-750',ne:'Trapezoidal Roofing Sheet 750mm — Deep Rib Heavy Duty',prof:'Trapezoidal (35mm deep rib)',thk:'0.40-0.80mm BMT',hero:'Deep Rib Trapezoidal 750',sub:'Deep 35mm Rib for Long Span Roofing up to 12m Without Purlins',badges:['📐 35mm Deep Rib','📏 750mm Cover','🏗️ Long Span','🏭 Heavy Duty'],seo:{t:'Deep Rib Trapezoidal Roofing Sheet 750mm | SunSea Steel',d:'Deep rib 35mm trapezoidal roof sheet 750mm cover. Heavy duty for long span roofing up to 12m purlin spacing.',k:'deep rib roofing, long span metal roof, 750 trapezoidal, heavy duty roof sheet, deep profile metal roof'}},
{n:'立边咬合屋面板 YX65-430',ne:'Standing Seam Roof Panel 430mm — Concealed Fastener',prof:'Standing Seam (65mm seam height)',thk:'0.40-0.80mm BMT',hero:'Standing Seam 430',sub:'Zero Exposed Fasteners — Premium Waterproof & Architectural Roofing',badges:['🔒 Concealed Fix','📏 430mm Panel','💎 Premium','🌧️ Zero Leak'],seo:{t:'Standing Seam Roof Panel 430mm | SunSea Steel',d:'Standing seam metal roofing 430mm panel. 65mm seam height. Zero exposed fasteners for premium waterproof performance.',k:'standing seam roof, concealed fastener roof, 430 standing seam, metal seam roof, premium metal roof'}},
{n:'立边咬合屋面板 YX65-300',ne:'Standing Seam Roof Panel 300mm — Narrow Premium',prof:'Standing Seam (65mm seam, 300mm panel)',thk:'0.50-0.80mm BMT',hero:'Standing Seam 300',sub:'Narrow Panel Premium — Modern Architectural Look with Defined Lines',badges:['🔒 Concealed Fix','📏 300mm Narrow','🏛️ Architectural','✨ Modern'],seo:{t:'Narrow Standing Seam Roof Panel 300mm | SunSea Steel',d:'Narrow 300mm standing seam roof panel for modern architecture. Defined seam lines for premium visual impact.',k:'narrow standing seam, 300mm standing seam, architectural metal roof, premium roof panel, modern seam roof'}},
{n:'琉璃瓦型彩钢板',ne:'Glazed Tile Effect Metal Roofing Sheet — Roman/Colonial Style',prof:'Glazed Tile Profile (wave tile)',thk:'0.30-0.60mm BMT',hero:'Tile Effect Metal Roof',sub:'Clay Tile Appearance with Metal Durability — Residential & Villa',badges:['🏛️ Tile Look','📏 1000mm Cover','🏠 Residential','💎 Villa'],seo:{t:'Glazed Tile Effect Metal Roofing Sheet | SunSea Steel',d:'Glazed tile effect metal roofing sheet. Clay tile appearance with steel durability for villas, residential, and heritage buildings.',k:'tile effect metal roof, glazed tile steel, clay tile metal, roman tile roof, metal tile sheet'}},
{n:'仿古瓦彩钢板',ne:'Spanish/Mediterranean Style Metal Roof Tile Sheet',prof:'S-Tile or Spanish Tile Profile',thk:'0.30-0.50mm BMT',hero:'Spanish Tile Metal Roof',sub:'Mediterranean Elegance — Curved Tile Look at a Fraction of the Weight',badges:['🏠 Mediterranean','📏 Custom Width','🏛️ Elegance','💨 Lightweight'],seo:{t:'Spanish Mediterranean Metal Roof Tile Sheet | SunSea Steel',d:'Spanish style metal roof tile sheet. Mediterranean curved tile aesthetics at 1/10 the weight of clay tiles.',k:'spanish tile metal roof, mediterranean roof, S-tile steel, curved metal tile, spanish style roofing'}},
{n:'彩石金属瓦',ne:'Stone Coated Metal Roofing Tile — Premium Residential',prof:'Stone-Coated Pressed Tile',thk:'0.40mm BMT steel + stone granule',hero:'Stone Coated Metal Tile',sub:'Natural Stone Finish — The Premium Choice for Luxury Homes',badges:['🪨 Stone Coated','📏 1340×420mm','🏠 Luxury','🌡️ 50yr Life'],seo:{t:'Stone Coated Metal Roofing Tile Premium | SunSea Steel',d:'Stone coated metal roofing tile for luxury residential. Natural stone granule finish, 50 year service life, lightweight.',k:'stone coated roof tile, metal roof tile, stone granule roof, premium roofing tile, luxury metal roof'}},
{n:'夹芯板 EPS芯材',ne:'EPS Sandwich Panel — Economy Insulated Roof & Wall',prof:'EPS Core Sandwich (50-200mm)',thk:'0.35-0.50mm face + EPS core',hero:'EPS Sandwich Panel',sub:'Budget Insulation — Polystyrene Core for Walls & Cool Rooms',badges:['🧊 EPS Insulated','📏 50-200mm Core','💰 Economy','🏗️ Wall/Roof'],seo:{t:'EPS Sandwich Panel Insulated Roof Wall | SunSea Steel',d:'EPS polystyrene core sandwich panel for insulated walls and roofing. Economy solution for temperature-controlled buildings.',k:'EPS sandwich panel, insulated wall panel, polystyrene roof panel, EPS insulated roof, sandwich panel economy'}},
{n:'夹芯板 PU芯材',ne:'PU/PIR Sandwich Panel — Premium Insulated Roof & Wall',prof:'PU/PIR Core Sandwich (30-150mm)',thk:'0.35-0.50mm face + PU/PIR core',hero:'PU Sandwich Panel',sub:'Premium Insulation — Best Thermal Performance per mm of Thickness',badges:['🔥 PU/PIR Core','📏 30-150mm','💎 Premium','🌡️ Best R-Value'],seo:{t:'PU PIR Sandwich Panel Premium Insulated | SunSea Steel',d:'PU/PIR core sandwich panel. Premium insulation with the best thermal performance per mm. B1 fire rating available.',k:'PU sandwich panel, PIR insulated panel, polyurethane roof panel, PU insulated wall, premium sandwich panel'}},
{n:'夹芯板 岩棉芯材',ne:'Rockwool/Mineral Wool Sandwich Panel — Fire Rated A1',prof:'Rockwool Core Sandwich (50-200mm)',thk:'0.40-0.50mm face + rockwool core',hero:'Rockwool Fire Panel',sub:'A1 Fire Rating — Non-Combustible Core for Fire Safety Compliance',badges:['🔥 A1 Fire Rated','📏 50-200mm','🏥 Code Required','🏭 Industrial'],seo:{t:'Rockwool Mineral Wool Sandwich Panel A1 Fire | SunSea Steel',d:'Rockwool core sandwich panel with A1 non-combustible fire rating. Required for high-rise, hospital, and fire-rated wall applications.',k:'rockwool sandwich panel, mineral wool panel, fire rated panel, A1 fire panel, non-combustible wall panel'}},
{n:'C型钢檩条',ne:'C-Purlin — Structural Roof and Wall Support',prof:'C-Section (75-300mm depth)',thk:'1.0-3.0mm',hero:'C-Purlin Steel',sub:'Structural Purlins and Girts for Metal Roof and Wall Systems',badges:['📐 C-Section','📏 75-300mm','🏗️ Structural','💪 350-550MPa'],seo:{t:'C-Purlin Steel Structural Roof Support | SunSea Steel',d:'C-section steel purlins for metal roof and wall support. 75-300mm depth, 350-550MPa yield. GI or GL coated.',k:'C purlin, steel purlin, roof purlin, C section purlin, structural purlin'}},
{n:'Z型钢檩条',ne:'Z-Purlin — Structural Roof and Wall Support',prof:'Z-Section (100-300mm depth)',thk:'1.0-3.0mm',hero:'Z-Purlin Steel',sub:'Asymmetric Section for Continuous Multi-Span Purlin Systems',badges:['📐 Z-Section','📏 100-300mm','🏗️ Multi-Span','💪 Structural'],seo:{t:'Z-Purlin Steel Structural Roof System | SunSea Steel',d:'Z-section steel purlins for multi-span metal roof systems. 100-300mm depth, continuous lap capability.',k:'Z purlin, steel Z purlin, roof Z section, structural Z purlin, continuous purlin'}},
{n:'屋面配件套装',ne:'Roof Accessory Kit — Ridge, Barge, Valley, Flashings & Fasteners',prof:'Complete Accessory Set',thk:'0.35-0.50mm (matching profile)',hero:'Roof Accessory Kit',sub:'Complete Set — Everything You Need to Finish a Metal Roof',badges:['🔧 Complete Kit','🎨 Color Matched','📦 All-in-One','🏠 Ready'],seo:{t:'Metal Roof Accessory Kit Flashings | SunSea Steel',d:'Complete metal roof accessory kit: ridge cap, barge flashing, valley gutter, fascia, downpipe, screws. All color-matched.',k:'roof accessories, ridge cap, barge flashing, valley gutter, roof flashing kit, metal roof fittings'}},
{n:'落水系统',ne:'Rain Gutter & Downpipe System — PPGI/PPGL',prof:'Half-Round / K-Style Gutter + Downpipe',thk:'0.40-0.55mm',hero:'Rain Gutter System',sub:'Complete Rainwater Collection — Gutters, Downpipes, Brackets & Outlets',badges:['🌧️ Rain System','📏 120-170mm','🎨 Color Matched','🏠 Residential'],seo:{t:'Rain Gutter Downpipe System PPGI | SunSea Steel',d:'Rain gutter and downpipe system in PPGI/PPGL. Half-round and K-style gutters with complete brackets and installation hardware.',k:'rain gutter system, metal downpipe, PPGI gutter, roof drainage, rainwater gutter system'}}
]
async function main(){
  let c=0
  for(const p of P){
    const ov=`<p><strong>${p.ne}</strong> featuring ${p.prof} profile. Available in GI, GL, PPGI, and PPGL substrates with full RAL color range. Profile formed to your specified length on our automated roll-forming lines with CNC cutting precision ±1mm.</p><p>Complete roofing solutions including matching ridge caps, barge flashings, valley gutters, and self-drilling fasteners. Technical span tables and wind load calculations available on request.</p>`
    const data={name:p.n,name_en:p.ne,category_id:C,description:p.ne,description_en:p.ne,
      specs:S(sp(p.prof,p.thk)),faq_items:S(fq.map(f=>({question:f.q,answer:f.a}))),is_featured:c<3?1:0,status:1,
      seo_title:p.seo.t,seo_description:p.seo.d,seo_keywords:p.seo.k,
      detail_content:productHtml({name:p.n,name_en:p.ne,hero:p.hero,sub:p.sub,badges:p.badges,accent:'#e74c3c',
        overview:ov,specs:sp(p.prof,p.thk),apps,faqs:fq})}
    const r=await upload('products',data);c++
    console.log(`✅ [${c}/15] ${p.ne} → id=${r.id}`)
  }
  console.log(`\n🎉 Cat5 Roofing: ${c} products done`)
}
main().catch(e=>console.error('❌',e))
