import{upload,productHtml}from'./tpl.mjs'
const C=6,S=JSON.stringify
const sp=(grade,thk,w)=>[{name:'Steel Grade',value:grade},{name:'Thickness',value:thk},{name:'Width',value:w||'600-1500mm'},{name:'Surface Finish',value:'Bright / Matte / 2B / BA / Stone Finish'},{name:'Yield Strength',value:'140-550 MPa (grade dependent)'},{name:'Coil Inner Diameter',value:'508mm / 610mm'},{name:'Standard',value:'ASTM A1008, EN 10130, JIS G3141, GB/T 708'}]
const apps=[{i:'🏠',t:'Home Appliances',d:'Refrigerator, washer, AC, microwave housings. Zero spangle surface for painting or PPGI substrate.'},{i:'🚗',t:'Automotive',d:'Body panels, chassis parts, structural members. IF/BH steel for drawability and dent resistance.'},{i:'🔧',t:'General Fabrication',d:'Shelving, enclosures, brackets, panels, furniture, ducting. Deep drawing and bending applications.'},{i:'🏗️',t:'Construction & Coated Steel',d:'Base substrate for GI, GL, PPGI, PPGL production. CQ to structural grades for coating lines.'}]
const fq=[{q:'What is cold rolled coil (CRC)?',a:'CRC is hot-rolled steel that has been further processed through cold reduction mills at room temperature. This cold working reduces thickness (typically 0.15-3.0mm), improves surface finish, tightens dimensional tolerances, and increases strength through strain hardening.'},{q:'What is the difference between CRC and HRC?',a:'HRC (hot rolled coil) is produced at 800-1200°C with thickness typically 1.2-25mm and rough surface (mill scale). CRC is produced from HRC at room temperature with thickness 0.15-3.0mm, smooth surface, and tighter tolerances (±0.02mm vs ±0.1mm for HRC).'},{q:'What does SPCC mean?',a:'SPCC stands for Steel Plate Cold Commercial — the JIS G3141 designation for commercial quality cold rolled steel. Equivalent to DC01 (EN 10130), A1008 CS Type B (ASTM). Used for general forming and bending applications.'},{q:'What is the difference between DC01 and DC03?',a:'DC01 (Commercial Quality): general bending and moderate forming. DC03 (Drawing Quality): deeper drawing capability with lower yield strength and higher elongation. DC04 (Deep Drawing) and DC05 (Extra Deep Drawing) provide progressively better drawability.'},{q:'Can CRC be welded?',a:'Yes. CRC welds easily with all common methods: MIG, TIG, spot welding, laser, and resistance seam welding. Low carbon content (typically 0.02-0.10%) ensures excellent weldability. No pre-heating required for standard grades.'},{q:'What is the MOQ?',a:'25 MT per specification for full containers. Mixed containers: 5 MT/spec minimum with 25 MT total. Trial orders from 5 MT available with adjusted pricing.'}]
const P=[
{n:'冷轧钢卷 SPCC/DC01',ne:'Cold Rolled Steel Coil SPCC/DC01 — Commercial Quality',grade:'SPCC / DC01 / A1008 CS-B',thk:'0.20-3.0mm',hero:'CRC SPCC/DC01',sub:'Commercial Quality — General Forming, Bending & Fabrication',badges:['📋 SPCC/DC01','📏 0.20-3.0mm','⭐ Standard CQ','🔧 General Use'],seo:{t:'Cold Rolled Steel Coil SPCC DC01 | SunSea Steel',d:'SPCC/DC01 commercial quality CRC for general forming and fabrication. 0.20-3.0mm, bright finish. Factory direct supply.',k:'cold rolled coil SPCC, DC01 CRC, commercial quality CRC, cold rolled steel coil, SPCC steel coil'}},
{n:'冷轧钢卷 SPCD/DC03',ne:'Cold Rolled Steel Coil SPCD/DC03 — Drawing Quality',grade:'SPCD / DC03 / A1008 DS-B',thk:'0.20-2.5mm',hero:'CRC SPCD/DC03',sub:'Drawing Quality — Deep Drawing Stampings & Complex Shapes',badges:['📋 SPCD/DC03','📏 0.20-2.5mm','🔧 Drawing','📐 Complex Shape'],seo:{t:'Cold Rolled Steel Coil SPCD DC03 Drawing | SunSea Steel',d:'SPCD/DC03 drawing quality CRC for deep drawn stampings and complex forming. Superior elongation and r-value.',k:'drawing quality CRC, DC03 cold rolled, SPCD steel, deep drawing coil, draw quality steel'}},
{n:'冷轧钢卷 SPCE/DC04',ne:'Cold Rolled Steel Coil SPCE/DC04 — Deep Drawing Quality',grade:'SPCE / DC04 / A1008 DDS',thk:'0.30-2.0mm',hero:'CRC SPCE/DC04',sub:'Deep Drawing Quality — Automotive Panels & Complex Stamping',badges:['📋 SPCE/DC04','📏 0.30-2.0mm','🚗 Automotive','📐 Deep Draw'],seo:{t:'Cold Rolled Steel Coil SPCE DC04 Deep Drawing | SunSea Steel',d:'SPCE/DC04 deep drawing CRC for automotive panels and complex stampings. High elongation, excellent r-value and n-value.',k:'deep drawing CRC, DC04 cold rolled, SPCE steel, automotive CRC, deep draw steel coil'}},
{n:'冷轧钢卷 DC05/SPCF',ne:'Cold Rolled Steel Coil DC05/SPCF — Extra Deep Drawing',grade:'DC05 / SPCF / IF Steel',thk:'0.40-2.0mm',hero:'CRC DC05 Extra Deep',sub:'Extra Deep Drawing — Complex Automotive & Appliance Stampings',badges:['📋 DC05/SPCF','📏 0.40-2.0mm','🚗 EDD Grade','🏆 Premium'],seo:{t:'Cold Rolled Steel Coil DC05 Extra Deep Drawing | SunSea Steel',d:'DC05/SPCF extra deep drawing CRC is an interstitial-free (IF) Steel for the most demanding automotive and appliance stampings.',k:'DC05 extra deep draw, SPCF CRC, IF steel coil, extra deep drawing steel, premium CRC automotive'}},
{n:'冷轧钢卷 DC06',ne:'Cold Rolled Steel Coil DC06 — Super Deep Drawing IF Steel',grade:'DC06 / IF-HS (Interstitial Free)',thk:'0.50-2.0mm',hero:'CRC DC06 Super Deep',sub:'Super Deep Drawing IF Steel — Extreme Forming for Complex Auto Parts',badges:['📋 DC06','📏 0.50-2.0mm','🏆 Super DDQ','🚗 Auto Body'],seo:{t:'Cold Rolled Steel Coil DC06 Super Deep Drawing | SunSea Steel',d:'DC06 super deep drawing interstitial-free cold rolled steel for the most complex automotive body stampings requiring extreme formability.',k:'DC06 CRC, super deep drawing, interstitial free steel, auto body steel, DC06 cold rolled'}},
{n:'高强度冷轧钢卷 S350GD',ne:'High Strength Cold Rolled Steel Coil S350GD — Structural Grade',grade:'S350GD / SPFH590 / A1008 SS Gr.50',thk:'0.50-3.0mm',hero:'High Strength CRC S350GD',sub:'350 MPa Yield — Structural Components, Purlins & Roll Formed Sections',badges:['💪 350 MPa','📏 0.50-3.0mm','🏗️ Structural','📐 Roll Form'],seo:{t:'High Strength CRC S350GD Structural | SunSea Steel',d:'S350GD high strength cold rolled coil. 350MPa yield for structural purlins, rack frames, and roll-formed sections.',k:'high strength CRC, S350GD cold rolled, structural CRC, high yield steel coil, S350GD steel'}},
{n:'镀锌基板用冷轧钢卷',ne:'Cold Rolled Coil for Galvanizing Line Substrate',grade:'CQ-DQ (Coating Line Grade)',thk:'0.15-3.0mm',hero:'CRC Galvanizing Substrate',sub:'Optimized Surface for Hot-Dip GI & GL Coating Lines',badges:['🏭 Coating Substrate','📏 0.15-3.0mm','🔧 CGL/CGL','⭐ Clean Surface'],seo:{t:'CRC for Galvanizing Line Substrate | SunSea Steel',d:'Cold rolled coil optimized for hot-dip galvanizing and Galvalume coating lines. Clean surface, controlled chemistry, tight gauge.',k:'CRC galvanizing substrate, GI base coil, cold rolled for coating, CGL substrate, CRC for PPGI'}},
{n:'烟蓝色冷轧钢卷',ne:'Cold Rolled Steel Coil Blue Annealed / Black Annealed',grade:'Blue Annealed / Black Annealed',thk:'0.15-2.0mm',hero:'Blue/Black Annealed CRC',sub:'Annealed Coil for Drum Making, Tube Welding & General Use',badges:['🔵 Blue Annealed','📏 0.15-2.0mm','🥫 Drum Making','🔩 Tube Stock'],seo:{t:'Blue Black Annealed CRC Cold Rolled | SunSea Steel',d:'Blue annealed and black annealed cold rolled steel for drum manufacturing, tube welding, and general purpose applications.',k:'blue annealed CRC, black annealed coil, annealed cold rolled, drum making steel, tube stock CRC'}},
{n:'冷轧钢板',ne:'Cold Rolled Steel Sheet — Flat Cut to Size',grade:'SPCC/DC01-DC04',thk:'0.30-3.0mm',hero:'CRC Flat Sheet',sub:'Pre-Cut Flat Panels for Stamping, Laser Cut, and Fabrication',badges:['📐 Custom Size','📏 0.30-3.0mm','🔧 Fab Ready','📦 Palletized'],seo:{t:'Cold Rolled Steel Sheet Flat Cut | SunSea Steel',d:'Cold rolled steel sheet cut to size for stamping, CNC cutting, laser cutting, and general sheet metal fabrication.',k:'cold rolled steel sheet, CRC flat sheet, cut CRC panel, CRC steel plate, flat cold rolled'}},
{n:'冷轧钢带',ne:'Cold Rolled Steel Strip — Precision Slit',grade:'SPCC-DC04 / Spring Steel',thk:'0.10-3.0mm, Width 10-600mm',hero:'CRC Precision Strip',sub:'Precision Slit Strip for Stamping, Springs, Blades & Components',badges:['📐 10-600mm Width','🔧 ±0.02mm','📏 0.10-3.0mm','🔩 Precision'],seo:{t:'Cold Rolled Steel Strip Precision Slit | SunSea Steel',d:'Precision slit cold rolled steel strip for stamping dies, springs, blades, and precision component manufacturing.',k:'cold rolled strip, CRC slit coil, precision steel strip, stamping strip, narrow cold rolled'}},
{n:'家电用冷轧钢卷',ne:'Appliance Grade Cold Rolled Coil — Zero Spangle Substrate',grade:'DC01-DC04 (Appliance Grade)',thk:'0.30-1.0mm',hero:'Appliance Grade CRC',sub:'Ultra-Smooth Surface for Pre-Coated Metal (PCM) & Appliance Panel',badges:['🏠 Appliance Grade','📏 0.30-1.0mm','✨ Ultra Smooth','🧊 PCM Ready'],seo:{t:'Appliance Grade CRC Zero Spangle | SunSea Steel',d:'Appliance grade cold rolled coil with ultra-smooth surface for PCM pre-coated metal, refrigerator, and washing machine panels.',k:'appliance CRC, zero spangle substrate, PCM cold rolled, appliance steel coil, smooth surface CRC'}},
{n:'汽车用冷轧钢卷',ne:'Automotive Grade Cold Rolled Coil — IF/BH/DP Steel',grade:'IF / BH / DP / TRIP',thk:'0.50-2.0mm',hero:'Automotive CRC',sub:'Advanced High Strength Steel for Body-in-White & Structural Parts',badges:['🚗 Auto Grade','📏 0.50-2.0mm','💪 AHSS','🏗️ BIW Parts'],seo:{t:'Automotive Cold Rolled Steel IF BH DP | SunSea Steel',d:'Automotive grade CRC: IF steel, BH (bake hardening), DP (dual phase), TRIP for body-in-white and structural components.',k:'automotive CRC, IF steel auto, bake hardening steel, dual phase CRC, auto body steel'}},
{n:'搪瓷用冷轧钢卷',ne:'Enamel Grade Cold Rolled Coil — For Porcelain Enameling',grade:'DC01EK / SPHE / Enamel Grade',thk:'0.40-1.5mm',hero:'Enamel Grade CRC',sub:'Optimized for Porcelain Enamel Coating — Water Heaters & Bathtubs',badges:['🛁 Enamel Grade','📏 0.40-1.5mm','🔥 Vitreous','💧 Water Heater'],seo:{t:'Enamel Grade CRC for Porcelain Coating | SunSea Steel',d:'Enamel grade cold rolled steel for porcelain enameling: water heaters, bathtubs, cookware, and chemical equipment.',k:'enamel grade CRC, porcelain enamel steel, enamel cold rolled, water heater steel, DC01EK steel'}},
{n:'弹簧用冷轧钢带',ne:'Spring Steel Cold Rolled Strip — High Carbon',grade:'C65-C85 / SK5-SK2 / 1074-1095',thk:'0.10-3.0mm, Width 10-300mm',hero:'Spring Steel Strip',sub:'High Carbon Spring Steel for Blades, Springs, Clips & Precision Parts',badges:['🔩 Spring Grade','📏 0.10-3.0mm','💪 High Carbon','⚙️ Precision'],seo:{t:'Spring Steel Cold Rolled Strip High Carbon | SunSea Steel',d:'High carbon spring steel strip C65-C85/SK5-SK2 for flat springs, blades, saw blades, clips, and precision components.',k:'spring steel strip, high carbon CRC, SK5 steel, blade steel strip, spring grade cold rolled'}},
{n:'低碳冷轧钢卷 08Al/SPCEN',ne:'Ultra Low Carbon Cold Rolled Coil (ULC/IF Base) — 08Al Grade',grade:'08Al / ULC / SPCEN',thk:'0.20-2.0mm',hero:'Ultra Low Carbon CRC',sub:'Ultra Low Carbon for Extreme Formability & Galvanizing Substrate',badges:['📋 08Al/ULC','📏 0.20-2.0mm','🔧 IF Base','✨ Exceptional'],seo:{t:'Ultra Low Carbon CRC 08Al IF Base | SunSea Steel',d:'Ultra low carbon cold rolled steel 08Al/ULC for extreme formability, tinplate substrate, and premium galvanizing applications.',k:'ultra low carbon CRC, 08Al steel, ULC cold rolled, IF base coil, low carbon CRC'}}
]
async function main(){
  let c=0
  for(const p of P){
    const ov=`<p><strong>${p.ne}</strong> featuring ${p.grade} grade specification with ${p.thk} thickness range. Cold rolled to precise dimensional tolerances (±0.02mm thickness, ±1mm width) with controlled surface roughness for downstream processing compatibility.</p><p>Produced on our continuous cold rolling mill with 20-hi Sendzimir backup rolls for excellent shape and flatness. All coils supplied with MTC per EN 10204 Type 3.1 including chemistry, mechanicals, and surface roughness.</p>`
    const data={name:p.n,name_en:p.ne,category_id:C,description:p.ne,description_en:p.ne,
      specs:S(sp(p.grade,p.thk)),faq_items:S(fq.map(f=>({question:f.q,answer:f.a}))),is_featured:c<3?1:0,status:1,
      seo_title:p.seo.t,seo_description:p.seo.d,seo_keywords:p.seo.k,
      detail_content:productHtml({name:p.n,name_en:p.ne,hero:p.hero,sub:p.sub,badges:p.badges,accent:'#e67e22',
        overview:ov,specs:sp(p.grade,p.thk),apps,faqs:fq})}
    const r=await upload('products',data);c++
    console.log(`✅ [${c}/15] ${p.ne} → id=${r.id}`)
  }
  console.log(`\n🎉 Cat6 CRC: ${c} products done`)
}
main().catch(e=>console.error('❌',e))
