import{upload,productHtml}from'./tpl.mjs'
const C=3,S=JSON.stringify
const sp=(paint,thk,sub)=>[{name:'Top Paint System',value:paint},{name:'Steel Thickness',value:thk},{name:'Substrate',value:sub||'GL AZ100-AZ150'},{name:'Width',value:'600-1250mm'},{name:'Top Coat Thickness',value:'15-25μm (PE/SMP) / 25-35μm (HDP/PVDF)'},{name:'Back Coat',value:'5-7μm primer or 15-20μm full coat'},{name:'Standard',value:'ASTM A755, EN 10169, JIS G3322, AS 2728'}]
const apps=[{i:'🏠',t:'Residential Roofing',d:'Corrugated, standing seam, and tile-profile panels for houses, villas, and apartments. 30+ color options. PVDF for coastal.'},{i:'🏭',t:'Industrial & Commercial',d:'Trapezoidal and IBR wall/roof panels for factories, warehouses, malls, and offices. HDP for durability.'},{i:'🏗️',t:'Pre-Engineered Buildings',d:'Wall and roof cladding for PEB structures. Custom color matching. Fire-rated sandwich panel facings.'},{i:'🎨',t:'Architectural & Decorative',d:'PVDF metallic finishes for premium facades, canopy soffits, column covers, and architectural features.'}]
const fq=[{q:'What paint systems are available?',a:'PE (Polyester, 15-20μm, 8-12yr), SMP (Silicon Modified Polyester, 18-22μm, 12-18yr), HDP (High Durability Polyester, 20-28μm, 18-25yr), PVDF (Polyvinylidene Fluoride, 25-35μm, 25-35yr). Choose based on UV exposure and warranty requirement.'},{q:'Why is PPGL better than PPGI?',a:'GL substrate corrodes 3-5× slower than GI substrate at paint damage sites. PPGL total system life is typically 30-40 years vs 20-25 for PPGI. The $40-80/MT premium delivers 10-15 extra years.'},{q:'What colors are available?',a:'Full RAL color range (200+ colors), plus metallic, wood-grain, stone-pattern, and camouflage finishes. MOQ for standard colors: 5MT. Custom colors: 25MT. Color matching to physical sample available.'},{q:'What is the warranty?',a:'PE: 8-10yr color warranty, SMP: 12-15yr, HDP: 18-20yr, PVDF: 25-30yr. Substrate warranty (perforation): 25-40yr depending on AZ coating weight.'},{q:'Can PPGL be bent and roll-formed?',a:'Yes. Standard PPGL can be roll-formed without paint cracking at radii ≥1T for PE/SMP and ≥2T for HDP/PVDF. Specify "forming grade" for tight radius requirements.'},{q:'What is the MOQ?',a:'5MT per color/spec for standard RAL colors. 25MT for custom colors. Mixed containers accepted with 25MT minimum total.'}]
const P=[
{n:'PE聚酯彩涂镀铝锌钢卷',ne:'PE Polyester PPGL Coil — Economy Color Roofing',paint:'PE Polyester (15-20μm)',thk:'0.14-0.80mm',hero:'PE Polyester PPGL',sub:'Economy Paint — 8-12yr Color Life for Budget Roofing & Interior',badges:['🎨 PE Paint','📏 0.14-0.80mm','💰 Economy','🏠 Budget Roof'],seo:{t:'PE Polyester PPGL Coil Economy | SunSea Steel',d:'PE polyester prepainted Galvalume coil. Economy grade for budget roofing, wall panels, and interior cladding.',k:'PE PPGL coil, polyester prepainted galvalume, economy color steel, PE coated GL, budget PPGL'}},
{n:'SMP硅改性聚酯彩涂镀铝锌钢卷',ne:'SMP Silicon Modified Polyester PPGL Coil — Standard',paint:'SMP (18-22μm)',thk:'0.20-0.80mm',hero:'SMP PPGL Steel',sub:'Standard Paint — 12-18yr Color Life for General Roofing & Cladding',badges:['🎨 SMP Paint','📏 0.20-0.80mm','⭐ Standard','🏗️ Cladding'],seo:{t:'SMP PPGL Coil Standard Grade | SunSea Steel',d:'SMP silicon modified polyester PPGL. Standard grade for general roofing, wall cladding, and industrial buildings.',k:'SMP PPGL, silicon modified polyester, standard PPGL coil, SMP color steel, mid-range prepainted'}},
{n:'HDP高耐候聚酯彩涂镀铝锌钢卷',ne:'HDP High Durability Polyester PPGL Coil — Premium',paint:'HDP (20-28μm)',thk:'0.25-0.80mm',hero:'HDP PPGL Steel',sub:'High Durability Paint — 18-25yr Color Life for Demanding Environments',badges:['🎨 HDP Paint','📏 0.25-0.80mm','💎 Premium','🌊 Coastal OK'],seo:{t:'HDP High Durability PPGL Coil | SunSea Steel',d:'HDP high durability polyester PPGL coil. 18-25 year color warranty for coastal, tropical, and industrial environments.',k:'HDP PPGL, high durability polyester, premium PPGL coil, HDP color steel, long life prepainted'}},
{n:'PVDF氟碳彩涂镀铝锌钢卷',ne:'PVDF Fluorocarbon PPGL Coil — Architectural Grade',paint:'PVDF 70/30 (25-35μm)',thk:'0.30-1.0mm',hero:'PVDF PPGL Steel',sub:'Architectural Grade — 25-35yr Color Life for Premium Facades & Coastal',badges:['🎨 PVDF 70/30','📏 0.30-1.0mm','🏆 Architectural','⏳ 25-35yr'],seo:{t:'PVDF Fluorocarbon PPGL Coil Architectural | SunSea Steel',d:'PVDF 70/30 fluorocarbon PPGL coil. Architectural grade for premium building facades, 25-35 year color and gloss warranty.',k:'PVDF PPGL, fluorocarbon prepainted, architectural PPGL, PVDF coated GL, premium facade steel'}},
{n:'木纹彩涂镀铝锌钢卷',ne:'Wood Grain Pattern PPGL Coil — Decorative',paint:'Wood Grain Print (25-30μm)',thk:'0.25-0.60mm',hero:'Wood Grain PPGL',sub:'Realistic Wood Texture — Fences, Fascia, Interior & Decorative Use',badges:['🌲 Wood Grain','📏 0.25-0.60mm','🎨 Decorative','🏠 Residential'],seo:{t:'Wood Grain Pattern PPGL Coil | SunSea Steel',d:'Wood grain pattern prepainted Galvalume coil. Realistic wood texture for fencing, fascia, interior walls, and decorative applications.',k:'wood grain PPGL, wood pattern steel, decorative PPGL coil, wood print galvalume, imitation wood steel'}},
{n:'石纹彩涂镀铝锌钢卷',ne:'Stone/Marble Pattern PPGL Coil — Premium Decorative',paint:'Stone/Marble Print (25-35μm)',thk:'0.30-0.60mm',hero:'Stone Pattern PPGL',sub:'Luxury Stone Finish — Facades, Feature Walls & Premium Interior',badges:['🪨 Stone Pattern','📏 0.30-0.60mm','💎 Luxury','🏛️ Facade'],seo:{t:'Stone Marble Pattern PPGL Coil | SunSea Steel',d:'Stone and marble pattern prepainted Galvalume coil for luxury facades, feature walls, and premium interior finishes.',k:'stone pattern PPGL, marble print steel, luxury PPGL coil, stone texture galvalume, premium decorative steel'}},
{n:'迷彩彩涂镀铝锌钢卷',ne:'Camouflage Pattern PPGL Coil — Military & Utility',paint:'Camouflage Print (25-30μm)',thk:'0.30-0.60mm',hero:'Camouflage PPGL',sub:'Military Pattern for Defense Structures, Shelters & Utility Buildings',badges:['🌿 Camo Pattern','📏 0.30-0.60mm','🎯 Military','🏕️ Utility'],seo:{t:'Camouflage Pattern PPGL Coil | SunSea Steel',d:'Camouflage pattern PPGL for military buildings, shelters, hunting blinds, and utility structures. Multiple camo patterns available.',k:'camouflage PPGL, camo steel coil, military pattern steel, camouflage galvalume, defense building steel'}},
{n:'哑光彩涂镀铝锌钢卷',ne:'Matte Finish PPGL Coil — Low Gloss Architectural',paint:'Matte PE/HDP (15-28μm, 10-30% gloss)',thk:'0.25-0.80mm',hero:'Matte Finish PPGL',sub:'Low Gloss Finish — Reduces Glare for Architectural & Airport Applications',badges:['✨ Matte Finish','📏 0.25-0.80mm','🏛️ Architectural','👁️ Anti-Glare'],seo:{t:'Matte Finish PPGL Coil Low Gloss | SunSea Steel',d:'Matte finish low gloss PPGL coil for architectural facades, airport buildings, and anti-glare applications. 10-30% gloss.',k:'matte PPGL, low gloss prepainted, anti-glare steel coil, matte finish galvalume, architectural matte steel'}},
{n:'抗菌彩涂镀铝锌钢卷',ne:'Antibacterial PPGL Coil — Food & Healthcare Grade',paint:'Antibacterial PE/HDP (18-28μm)',thk:'0.30-0.80mm',hero:'Antibacterial PPGL',sub:'Antimicrobial Paint — Clean Rooms, Hospitals, Food Processing',badges:['🦠 Antibacterial','📏 0.30-0.80mm','🏥 Healthcare','🍖 Food Grade'],seo:{t:'Antibacterial PPGL Coil Healthcare Food Grade | SunSea Steel',d:'Antibacterial prepainted Galvalume for hospitals, clean rooms, food processing plants. ISO 22196 tested antimicrobial coating.',k:'antibacterial PPGL, antimicrobial steel coil, healthcare PPGL, food grade prepainted, hospital wall steel'}},
{n:'彩涂镀铝锌钢板',ne:'PPGL Steel Sheet — Flat Cut Color Panels',paint:'PE/SMP/HDP/PVDF',thk:'0.25-1.0mm',hero:'PPGL Color Sheet',sub:'Pre-Cut Color Panels for Cladding, Signage & Custom Fabrication',badges:['📐 Custom Cut','📏 Custom Length','🎨 Any Color','🔧 Fab Ready'],seo:{t:'PPGL Prepainted Galvalume Sheet | SunSea Steel',d:'PPGL color steel sheet cut to size. PE, SMP, HDP, PVDF paint systems on Galvalume substrate for any application.',k:'PPGL sheet, prepainted galvalume sheet, color steel panel, cut PPGL, flat color steel'}},
{n:'彩涂镀铝锌钢带',ne:'PPGL Steel Strip — Slit Color Coil',paint:'PE/SMP/HDP',thk:'0.20-0.80mm, Width 20-600mm',hero:'PPGL Color Strip',sub:'Precision Slit Color Strip for Venetian Blinds, Trim & Components',badges:['📐 20-600mm','🔧 ±0.1mm','🎨 Color Strip','🔩 Components'],seo:{t:'PPGL Slit Color Strip Coil | SunSea Steel',d:'PPGL precision slit color strip for venetian blinds, trim, rain gutters, and component manufacturing.',k:'PPGL strip, color slit coil, prepainted strip, venetian blind steel, PPGL narrow strip'}},
{n:'白灰色彩涂镀铝锌钢卷 RAL9002/9006',ne:'PPGL White/Silver Grey RAL 9002/9006 — Most Popular Colors',paint:'PE/SMP/HDP (Standard RAL)',thk:'0.20-0.80mm',hero:'PPGL White/Grey',sub:'Best Sellers — RAL 9002 Grey White & RAL 9006 Silver for Roofing',badges:['⚪ RAL 9002','🔘 RAL 9006','⭐ Best Seller','🏠 Roofing'],seo:{t:'PPGL White Silver Grey RAL 9002 9006 | SunSea Steel',d:'PPGL RAL 9002 grey white and RAL 9006 white aluminium. Most popular PPGL colors for roofing and cladding worldwide.',k:'PPGL RAL 9002, PPGL RAL 9006, white PPGL coil, silver grey prepainted, popular PPGL colors'}},
{n:'蓝色彩涂镀铝锌钢卷 RAL5015/5012',ne:'PPGL Blue RAL 5015/5012 — Sky Blue & Light Blue',paint:'PE/SMP/HDP (Blue RAL)',thk:'0.20-0.80mm',hero:'PPGL Blue Series',sub:'Popular Blue Tones for Residential & Commercial Roofing',badges:['🔵 RAL 5015','🔵 RAL 5012','🏠 Residential','🏗️ Commercial'],seo:{t:'PPGL Blue RAL 5015 5012 Sky Blue | SunSea Steel',d:'PPGL blue prepainted Galvalume. RAL 5015 sky blue and RAL 5012 light blue for residential and commercial roofing panels.',k:'PPGL blue coil, blue prepainted steel, RAL 5015 PPGL, sky blue roofing, blue color steel'}},
{n:'红色彩涂镀铝锌钢卷 RAL3011/3009',ne:'PPGL Red/Brick RAL 3011/3009 — Oxide Red & Maroon',paint:'PE/SMP/HDP (Red RAL)',thk:'0.20-0.80mm',hero:'PPGL Red Series',sub:'Classic Red Tones for Traditional & Residential Roofing',badges:['🔴 RAL 3011','🔴 RAL 3009','🏡 Traditional','🏠 Residential'],seo:{t:'PPGL Red Oxide RAL 3011 3009 | SunSea Steel',d:'PPGL red oxide and brick red. RAL 3011 and RAL 3009 for traditional and residential roofing applications.',k:'PPGL red coil, oxide red prepainted, RAL 3011 PPGL, brick red roofing, red color steel'}},
{n:'绿色彩涂镀铝锌钢卷 RAL6005/6024',ne:'PPGL Green RAL 6005/6024 — Moss Green & Traffic Green',paint:'PE/SMP/HDP (Green RAL)',thk:'0.20-0.80mm',hero:'PPGL Green Series',sub:'Natural Green Tones for Rural, Agricultural & Residential Roofing',badges:['🟢 RAL 6005','🟢 RAL 6024','🌿 Rural','🏡 Residential'],seo:{t:'PPGL Green RAL 6005 6024 Moss Green | SunSea Steel',d:'PPGL green prepainted Galvalume. RAL 6005 moss green and RAL 6024 for rural, agricultural, and residential roofing.',k:'PPGL green coil, green prepainted steel, RAL 6005 PPGL, moss green roofing, green color steel'}}
]
async function main(){
  let c=0
  for(const p of P){
    const ov=`<p><strong>${p.ne}</strong> featuring ${p.paint} paint system on Galvalume (55% Al-Zn) substrate. The combination of premium paint protection and GL's superior barrier corrosion resistance creates the longest-lasting prepainted steel system available.</p><p>Produced on our high-speed coil coating line with 4-roller precision application, infrared curing, and inline color measurement. All coils supplied with color board sample, MTC, and paint test certificate.</p>`
    const data={name:p.n,name_en:p.ne,category_id:C,description:p.ne,description_en:p.ne,
      specs:S(sp(p.paint,p.thk)),faq_items:S(fq.map(f=>({question:f.q,answer:f.a}))),is_featured:c<3?1:0,status:1,
      seo_title:p.seo.t,seo_description:p.seo.d,seo_keywords:p.seo.k,
      detail_content:productHtml({name:p.n,name_en:p.ne,hero:p.hero,sub:p.sub,badges:p.badges,accent:'#8e44ad',
        overview:ov,specs:sp(p.paint,p.thk),apps,faqs:fq})}
    const r=await upload('products',data);c++
    console.log(`✅ [${c}/15] ${p.ne} → id=${r.id}`)
  }
  console.log(`\n🎉 Cat3 PPGL: ${c} products done`)
}
main().catch(e=>console.error('❌',e))
