import{upload,productHtml}from'./tpl.mjs'
const C=4,S=JSON.stringify
const sp=(paint,thk,sub)=>[{name:'Top Paint System',value:paint},{name:'Steel Thickness',value:thk},{name:'Substrate',value:sub||'GI Z60-Z150'},{name:'Width',value:'600-1250mm'},{name:'Top Coat Thickness',value:'15-25μm (PE/SMP) / 25-35μm (HDP/PVDF)'},{name:'Back Coat',value:'5-7μm primer or 15-20μm full coat'},{name:'Standard',value:'ASTM A755, EN 10169, JIS G3312, GB/T 12754'}]
const apps=[{i:'🏠',t:'Residential Roofing & Walls',d:'Corrugated roofing panels, wall cladding, fascia, soffit panels for houses, villas, and apartments. Economical color solution.'},{i:'🏗️',t:'Commercial & Industrial',d:'Factory wall panels, warehouse cladding, retail store fronts, office building exteriors. SMP/HDP for commercial grade.'},{i:'🏠',t:'Home Appliances',d:'Refrigerator side panels, washing machine tops, microwave housings, water heater outer shells. Zero spangle GI substrate.'},{i:'📦',t:'Storage & Containers',d:'Container panels, storage units, garage doors, roller shutters, partition walls, portable cabins.'}]
const fq=[{q:'What is the difference between PPGI and PPGL?',a:'PPGI uses GI (galvanized) substrate; PPGL uses GL (Galvalume) substrate. PPGL has better scratch/undercutting resistance and 10-15yr longer system life but costs $40-80/MT more. PPGI is more economical for budget projects and interior applications.'},{q:'What paint systems are available for PPGI?',a:'PE (Polyester, 8-12yr color), SMP (Silicon Modified Polyester, 12-18yr), HDP (High Durability Polyester, 18-25yr), PVDF (Fluorocarbon, 25-35yr). PPGI most commonly uses PE and SMP.'},{q:'What colors are available?',a:'Full RAL range (200+ colors), plus metallic, wood grain, stone pattern, brick pattern, and camouflage. Standard colors: 5MT MOQ. Custom: 25MT.'},{q:'Can PPGI be bent without cracking?',a:'Yes. PE/SMP can be bent at 0T-1T radius. HDP: 1T-2T. PVDF: 2T-3T. Specify forming grade for tight radius requirements.'},{q:'What is the delivery time?',a:'Standard RAL colors: 15-20 days. Custom colors: 20-30 days (includes sample approval time). Shipping: FOB 3-5 days, CIF to SE Asia typically 10-20 days ocean.'},{q:'Is PPGI suitable for coastal environments?',a:'PPGI PE/SMP is acceptable for sheltered coastal (>5km from coast). For exposed coastal (<5km), we strongly recommend PPGL instead of PPGI due to GL substrate\'s superior corrosion resistance at paint damage sites.'}]
const P=[
{n:'PE聚酯彩涂镀锌钢卷',ne:'PE Polyester PPGI Coil — Economy Color Steel',paint:'PE Polyester (15-20μm)',thk:'0.14-0.80mm',hero:'PE Polyester PPGI',sub:'Budget-Friendly Color — 8-12yr for Roofing, Walls & Interior',badges:['🎨 PE Paint','📏 0.14-0.80mm','💰 Economy','🏠 Budget'],seo:{t:'PE Polyester PPGI Coil Economy | SunSea Steel',d:'PE polyester prepainted galvanized coil for budget roofing, wall panels, and interior cladding. Factory direct pricing.',k:'PE PPGI, polyester prepainted, economy color steel, PE coated GI, budget PPGI coil'}},
{n:'SMP硅改性聚酯彩涂镀锌钢卷',ne:'SMP Silicon Modified Polyester PPGI Coil — Standard',paint:'SMP (18-22μm)',thk:'0.20-0.80mm',hero:'SMP PPGI Steel',sub:'Standard Color — 12-18yr for General Roofing & Commercial Use',badges:['🎨 SMP Paint','📏 0.20-0.80mm','⭐ Standard','🏗️ Commercial'],seo:{t:'SMP PPGI Coil Standard Grade | SunSea Steel',d:'SMP silicon modified polyester PPGI coil. Standard grade for general roofing, wall cladding, and commercial buildings.',k:'SMP PPGI, silicon modified polyester GI, standard PPGI, SMP color steel, mid-range PPGI'}},
{n:'HDP高耐候聚酯彩涂镀锌钢卷',ne:'HDP High Durability Polyester PPGI Coil — Premium',paint:'HDP (20-28μm)',thk:'0.25-0.80mm',hero:'HDP PPGI Steel',sub:'High Durability — 18-25yr for Demanding Projects',badges:['🎨 HDP Paint','📏 0.25-0.80mm','💎 Premium','💪 Durable'],seo:{t:'HDP High Durability PPGI Coil Premium | SunSea Steel',d:'HDP high durability polyester PPGI coil for demanding environments. 18-25 year color warranty performance.',k:'HDP PPGI, high durability PPGI, premium prepainted GI, HDP color steel, long life PPGI'}},
{n:'PVDF氟碳彩涂镀锌钢卷',ne:'PVDF Fluorocarbon PPGI Coil — Architectural Grade',paint:'PVDF 70/30 (25-35μm)',thk:'0.30-1.0mm',hero:'PVDF PPGI Steel',sub:'Architectural Grade — 25-35yr Color for Premium Projects',badges:['🎨 PVDF 70/30','📏 0.30-1.0mm','🏆 Architectural','⏳ 25-35yr'],seo:{t:'PVDF PPGI Coil Architectural Grade | SunSea Steel',d:'PVDF fluorocarbon PPGI coil for architectural facades and premium buildings. 25-35 year color and gloss warranty.',k:'PVDF PPGI, fluorocarbon prepainted GI, architectural PPGI, PVDF coated galvanized, premium facade PPGI'}},
{n:'木纹彩涂镀锌钢卷',ne:'Wood Grain Pattern PPGI Coil — Decorative',paint:'Wood Grain Print (25-30μm)',thk:'0.25-0.60mm',hero:'Wood Grain PPGI',sub:'Natural Wood Look — Fencing, Doors, Interior & Furniture',badges:['🌲 Wood Grain','📏 0.25-0.60mm','🎨 Decorative','🏠 Interior'],seo:{t:'Wood Grain Pattern PPGI Coil | SunSea Steel',d:'Wood grain prepainted galvanized coil for fencing, doors, interior walls, furniture, and decorative applications.',k:'wood grain PPGI, wood pattern steel GI, decorative PPGI, wood print galvanized, imitation wood PPGI'}},
{n:'砖纹彩涂镀锌钢卷',ne:'Brick Pattern PPGI Coil — Premium Decorative',paint:'Brick Pattern Print (25-35μm)',thk:'0.30-0.60mm',hero:'Brick Pattern PPGI',sub:'Realistic Brick Finish for External & Internal Wall Panels',badges:['🧱 Brick Pattern','📏 0.30-0.60mm','💎 Premium','🏛️ Wall Panel'],seo:{t:'Brick Pattern PPGI Steel Coil | SunSea Steel',d:'Brick pattern prepainted galvanized steel for external and internal wall panels. Realistic brick texture without masonry.',k:'brick pattern steel, PPGI brick print, decorative wall panel, faux brick steel, brick texture PPGI'}},
{n:'哑光彩涂镀锌钢卷',ne:'Matte Finish PPGI Coil — Low Gloss',paint:'Matte PE/HDP (10-30% gloss)',thk:'0.25-0.80mm',hero:'Matte PPGI Steel',sub:'Low Gloss Finish — Anti-Glare for Architecture & Modern Design',badges:['✨ Matte Finish','📏 0.25-0.80mm','🏛️ Modern','👁️ Anti-Glare'],seo:{t:'Matte Finish PPGI Coil Low Gloss | SunSea Steel',d:'Matte finish low gloss PPGI coil for modern architectural design, anti-glare applications, and contemporary aesthetics.',k:'matte PPGI, low gloss prepainted, anti-glare PPGI, matte finish color steel, matte coated galvanized'}},
{n:'高光泽彩涂镀锌钢卷',ne:'High Gloss PPGI Coil — Mirror-Like Finish',paint:'High Gloss PE (80-95% gloss)',thk:'0.25-0.60mm',hero:'High Gloss PPGI',sub:'Mirror-Bright Finish for Appliances, Signage & Premium Products',badges:['✨ High Gloss','📏 0.25-0.60mm','🪞 Mirror Finish','🏠 Appliance'],seo:{t:'High Gloss PPGI Coil Mirror Finish | SunSea Steel',d:'High gloss (80-95% GU) PPGI for appliances, signage, and premium products. Mirror-like smooth finish on galvanized substrate.',k:'high gloss PPGI, mirror finish steel, glossy color coated, appliance PPGI, shiny prepainted GI'}},
{n:'花纹彩涂镀锌钢板',ne:'Embossed/Textured PPGI Coil — 3D Surface',paint:'PE/SMP + Embossing',thk:'0.25-0.60mm',hero:'Embossed PPGI Steel',sub:'3D Textured Surface for Panel, Door & Decorative Applications',badges:['🔲 Embossed','📏 0.25-0.60mm','🎨 3D Textured','🚪 Door Panel'],seo:{t:'Embossed Textured PPGI Coil 3D Surface | SunSea Steel',d:'Embossed and textured PPGI coil with 3D surface patterns for door panels, wall panels, and decorative steel applications.',k:'embossed PPGI, textured color steel, 3D surface PPGI, embossed door panel, textured galvanized coil'}},
{n:'家电用彩涂镀锌钢卷',ne:'Appliance Grade PPGI Coil — PCM Steel',paint:'PCM (Pre-Coated Metal, 15-20μm)',thk:'0.30-1.0mm',hero:'Appliance PPGI PCM',sub:'Pre-Coated Metal for White Goods, Panels & Enclosures',badges:['🏠 Appliance Grade','📏 0.30-1.0mm','🧊 White Goods','🔧 PCM Steel'],seo:{t:'Appliance Grade PPGI PCM Steel | SunSea Steel',d:'Appliance grade PPGI (PCM) for refrigerators, washing machines, microwaves, and industrial enclosures. Zero spangle substrate.',k:'appliance PPGI, PCM steel, pre-coated metal, white goods steel, appliance grade color coated'}},
{n:'彩涂镀锌钢板',ne:'PPGI Color Steel Sheet — Flat Cut Panels',paint:'PE/SMP/HDP/PVDF',thk:'0.25-1.0mm',hero:'PPGI Color Sheet',sub:'Pre-Cut Color Panels for Cladding, Signs & Custom Projects',badges:['📐 Custom Cut','📏 Custom Length','🎨 Any Color','🔧 Ready-to-Use'],seo:{t:'PPGI Color Steel Sheet Flat Cut | SunSea Steel',d:'PPGI color steel sheet cut to size for cladding, signage, partitions, and custom fabrication projects.',k:'PPGI sheet, color steel sheet, cut PPGI panel, flat color galvanized, prepainted GI sheet'}},
{n:'彩涂镀锌钢带',ne:'PPGI Color Steel Strip — Precision Slit',paint:'PE/SMP (15-22μm)',thk:'0.20-0.60mm, Width 20-600mm',hero:'PPGI Color Strip',sub:'Narrow Strip for Blinds, Trim, Edge Bands & Components',badges:['📐 20-600mm','🔧 Precision','🎨 Color Strip','🪟 Blinds'],seo:{t:'PPGI Color Slit Strip Coil | SunSea Steel',d:'PPGI precision slit color strip for venetian blinds, edge banding, trim profiles, and component manufacturing.',k:'PPGI strip, color slit steel, prepainted strip coil, venetian blind PPGI, narrow color steel'}},
{n:'白色彩涂镀锌钢卷 RAL9003',ne:'PPGI White RAL 9003 — Signal White',paint:'PE/SMP/HDP (Signal White)',thk:'0.20-0.80mm',hero:'PPGI White RAL 9003',sub:'Pure White — Most Popular for Interior, Appliances & Clean Surfaces',badges:['⚪ RAL 9003','⭐ Best Seller','📏 0.20-0.80mm','🏠 Interior'],seo:{t:'PPGI White RAL 9003 Signal White | SunSea Steel',d:'PPGI white RAL 9003 signal white. Most popular color for interior panels, appliances, and ceiling applications.',k:'PPGI white, RAL 9003 steel, white color coated, white PPGI coil, signal white prepainted'}},
{n:'海蓝色彩涂镀锌钢卷 RAL5015',ne:'PPGI Sea Blue RAL 5015 — Most Popular Roofing Color',paint:'PE/SMP/HDP (Sky Blue)',thk:'0.20-0.80mm',hero:'PPGI Blue RAL 5015',sub:'Sky Blue — The World\'s Most Popular Metal Roofing Color',badges:['🔵 RAL 5015','⭐ #1 Roof Color','📏 0.20-0.80mm','🌏 Global Hit'],seo:{t:'PPGI Blue RAL 5015 Most Popular Roofing | SunSea Steel',d:'PPGI blue RAL 5015 sky blue — the world\'s most popular metal roofing color for residential and commercial buildings.',k:'PPGI blue, RAL 5015 steel, sky blue roofing, blue PPGI coil, popular roof color blue'}},
{n:'灰色彩涂镀锌钢卷 RAL7035',ne:'PPGI Light Grey RAL 7035 — Industrial & Commercial Standard',paint:'PE/SMP/HDP (Light Grey)',thk:'0.20-0.80mm',hero:'PPGI Grey RAL 7035',sub:'Industrial Standard Grey — Factories, Warehouses & Commercial Walls',badges:['🔘 RAL 7035','🏭 Industrial','📏 0.20-0.80mm','🏗️ Commercial'],seo:{t:'PPGI Light Grey RAL 7035 Industrial | SunSea Steel',d:'PPGI light grey RAL 7035 for industrial wall cladding, warehouse panels, and commercial building exteriors.',k:'PPGI grey, RAL 7035 steel, light grey PPGI, industrial color steel, grey wall cladding'}}
]
async function main(){
  let c=0
  for(const p of P){
    const ov=`<p><strong>${p.ne}</strong> featuring ${p.paint} paint system on galvanized (GI) substrate. PPGI is the most economical prepainted steel option, combining the cost-effectiveness of zinc-coated substrate with color protection for roofing, cladding, and interior applications.</p><p>Produced on our high-speed coil coating line with 4-roller precision application. All coils supplied with color board sample, MTC, and paint test certificate per EN 10169.</p>`
    const data={name:p.n,name_en:p.ne,category_id:C,description:p.ne,description_en:p.ne,
      specs:S(sp(p.paint,p.thk)),faq_items:S(fq.map(f=>({question:f.q,answer:f.a}))),is_featured:c<3?1:0,status:1,
      seo_title:p.seo.t,seo_description:p.seo.d,seo_keywords:p.seo.k,
      detail_content:productHtml({name:p.n,name_en:p.ne,hero:p.hero,sub:p.sub,badges:p.badges,accent:'#3498db',
        overview:ov,specs:sp(p.paint,p.thk),apps,faqs:fq})}
    const r=await upload('products',data);c++
    console.log(`✅ [${c}/15] ${p.ne} → id=${r.id}`)
  }
  console.log(`\n🎉 Cat4 PPGI: ${c} products done`)
}
main().catch(e=>console.error('❌',e))
